import {test,expect} from '@playwright/test';
test('cockpit, walk, question, six discoveries and Mars',async({page},info)=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByRole('heading',{name:'Something is down there.'})).toBeVisible();
 await page.getByRole('button',{name:'Land on the Moon'}).click();await expect(page.getByLabel('Flight controls')).toBeVisible();await expect(page.locator('canvas')).toHaveCount(1);await expect(page.getByRole('heading',{name:'APOLLO 11',exact:true})).toHaveCount(0);await expect(page.locator('.cockpit-screen')).toHaveCount(2);await expect(page.getByLabel('Flight measurements')).toBeVisible();await expect(page.getByLabel('Landing map')).toBeVisible();await expect.poll(async()=>Number(await page.getByLabel('Flight controls').getAttribute('data-altitude')),{timeout:20000}).toBeLessThan(99.5);await page.keyboard.down('KeyD');await expect.poll(async()=>Number(await page.getByLabel('Flight controls').getAttribute('data-drift')),{timeout:15000}).toBeGreaterThan(.5);await expect(page.getByRole('button',{name:'Flight assist on'})).toHaveAttribute('aria-pressed','true');await page.screenshot({path:`docs/qa/open-canopy/${info.project.name}-steering.png`});await page.keyboard.up('KeyD');await page.getByRole('button',{name:'Pause flight',exact:true}).click();const height=await page.getByLabel('Flight controls').getAttribute('data-altitude');await page.waitForTimeout(250);expect(await page.getByLabel('Flight controls').getAttribute('data-altitude')).toBe(height);await page.screenshot({path:`docs/qa/open-canopy/${info.project.name}-cockpit.png`});await page.getByRole('button',{name:'Resume flight',exact:true}).first().click();
 await page.getByRole('heading',{name:'Follow the footprints.'}).waitFor({timeout:90000});await expect(page.getByRole('button',{name:'Scan the unknown hardware'})).toHaveCount(0);await page.keyboard.down('KeyW');await page.waitForTimeout(1100);await page.keyboard.up('KeyW');await page.screenshot({path:`docs/qa/open-canopy/${info.project.name}-walk.png`});
 if(info.project.name==='mobile-reduced')await page.getByRole('button',{name:'Skip walk'}).click();else{await page.keyboard.down('KeyW');await page.getByRole('button',{name:'Scan the unknown hardware'}).waitFor({timeout:60000});await page.keyboard.up('KeyW');}
 await page.getByRole('button',{name:'Scan the unknown hardware',exact:true}).click({timeout:10000});await expect(page.getByRole('heading',{name:'APOLLO 11',exact:true})).toBeVisible();await expect(page.locator('.quiz-options button')).toHaveCount(3);await page.locator('.quiz-options button').first().click();await expect(page.getByRole('status')).toContainText(/You got it|Good guess/);await page.screenshot({path:`docs/qa/open-canopy/${info.project.name}-cat.png`});await page.getByRole('button',{name:'Let’s explore'}).click();
 const eagle=page.locator('.discovery-dock [data-artifact="eagle"]');await eagle.click();await expect(page.getByRole('region',{name:'Artifact inspection'})).toBeVisible();await expect(page.getByRole('button',{name:/Inspect all parts/})).toBeDisabled();await page.getByRole('button',{name:'Close cross-section'}).click();await page.getByRole('button',{name:'Reconstruct full Eagle'}).click();await page.screenshot({path:`docs/qa/open-canopy/${info.project.name}-full-eagle.png`});await page.getByRole('button',{name:'Show what remained'}).click();await page.getByRole('button',{name:'Open cross-section'}).click();await page.getByRole('button',{name:'02 / Descent engine',exact:true}).click();await expect(page.getByRole('complementary',{name:'Engine learning poster'})).toBeVisible();await expect(page.locator('.part-poster h3')).toHaveText('Engine');await page.locator('.poster-art img').evaluate((img:HTMLImageElement)=>img.decode());await expect(page.locator('.poster-art img')).toHaveAttribute('src','/references/engine-poster.png');await page.screenshot({path:`docs/qa/open-canopy/${info.project.name}-engine-poster.png`});await page.locator('.component-switch').getByRole('button',{name:/Landing gear/}).click();await expect(page.locator('.part-poster')).toContainText('Four legs');await expect(page.locator('.part-poster img').first()).toHaveAttribute('src','/textures/alien-cat.png');await page.getByRole('button',{name:'Separate hardware'}).click();await page.getByRole('button',{name:'Assemble hardware'}).click();await page.getByText('More model controls',{exact:true}).click();await page.getByRole('button',{name:'Isolate selection'}).click();await page.getByRole('button',{name:'Show all parts'}).click();await page.getByRole('button',{name:'Rotate model left'}).click();await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Reset view'}).click();await page.getByText('More model controls',{exact:true}).click();await page.screenshot({path:`docs/qa/open-canopy/${info.project.name}-cutaway.png`});await page.keyboard.press('Escape');await expect.poll(()=>page.evaluate(()=>document.activeElement?.getAttribute('data-artifact'))).toBe('eagle');await eagle.click();await page.locator('.exit-inspection').click();await expect(page.getByRole('region',{name:'Artifact inspection'})).toHaveCount(0);await eagle.click();await page.locator('.component-switch').getByRole('button',{name:/Engine/}).click();await page.locator('.component-switch').getByRole('button',{name:/Landing gear/}).click();await page.getByRole('button',{name:'Archive discovery',exact:true}).click();
 for(const id of ['footprints','camera','seismometer','reflector','messages']){
  await page.locator(`.discovery-dock [data-artifact="${id}"]`).click();await expect(page.getByRole('button',{name:'Investigation incomplete'})).toBeDisabled();
  if(id==='footprints')await page.getByLabel('Evidence exposure').fill('100');
  else if(id==='reflector'){await page.getByLabel('Beam alignment').fill('0');await page.getByRole('button',{name:'Transmit pulse'}).click();}
  else await page.getByRole('button',{name:id==='camera'?'Follow the signal':id==='seismometer'?'Listen for moonquakes':'Read the message',exact:true}).click();
  await expect(page.locator('.evidence-conclusion')).toBeVisible();await page.getByText('Field note & NASA source',{exact:true}).click();await expect(page.locator('.interpretation a')).toHaveAttribute('href',/nasa.gov/);await page.getByText('Field note & NASA source',{exact:true}).click();await page.screenshot({path:`docs/qa/open-canopy/${info.project.name}-${id}.png`});await page.getByRole('button',{name:'Archive discovery',exact:true}).click();
 }
 await expect(page.getByRole('heading',{name:'These objects were not waste. They were evidence.'})).toBeVisible();await page.screenshot({path:`docs/qa/open-canopy/${info.project.name}-conclusion.png`});await page.getByRole('button',{name:'Listen beyond the Moon'}).click();await expect(page.getByRole('heading',{name:'MARS',exact:true})).toBeVisible();await page.getByRole('button',{name:'Read the expedition archive'}).click();await expect(page.getByRole('dialog')).toContainText('6 of 6 discoveries');await page.keyboard.press('Escape');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();expect(errors).toEqual([]);await page.getByRole('button',{name:'Restart expedition'}).click();await expect(page.getByRole('heading',{name:'Something is down there.'})).toBeVisible();
});
test('manual missed landing recovers and can retry',async({page})=>{test.setTimeout(90000);await page.goto('/');await page.getByRole('button',{name:'Land on the Moon'}).click();await page.getByRole('button',{name:'Flight assist on'}).click();await page.getByRole('button',{name:'Retry landing'}).waitFor({timeout:70000});await expect(page.getByRole('alert')).toContainText('Outside the landing zone');await page.getByRole('button',{name:'Retry landing'}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect.poll(async()=>Number(await page.getByLabel('Flight controls').getAttribute('data-altitude'))).toBeGreaterThan(80);await page.getByRole('button',{name:'Pause flight',exact:true}).click();});
