import { test, expect, type Page } from '@playwright/test';
async function visit(page:Page){await page.goto('/');await page.locator('.archive-index-trigger').click();await page.getByRole('button',{name:/05.*VOYAGER/}).click();await expect(page.locator('canvas')).toHaveAttribute('data-world','voyager',{timeout:40000});await page.getByRole('button',{name:'Approach the distant traveler'}).click();}
async function scan(page:Page,id:string){await page.locator(`.voyager-dock [data-artifact="${id}"]`).click();await page.getByRole('button',{name:'Scan object',exact:true}).click();await expect(page.locator('.mars-scan-panel')).toHaveCount(0,{timeout:15000});}
test('Voyager full journey, mystery gates, hardware, evidence and archive persistence',async({page})=>{
 test.setTimeout(150000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await visit(page);await page.locator('canvas').evaluate(el=>el.setAttribute('data-persistent','voyager'));
 await expect(page.locator('.voyager-dock')).not.toContainText('Golden Record');await expect(page.locator('[data-artifact="voyagerMessage"]')).toHaveCount(0);
 await page.waitForTimeout(1800);await page.screenshot({path:'docs/qa/voyager-desktop-surface.png'});await scan(page,'voyager');await expect(page.getByRole('button',{name:/Inspect all parts/})).toBeDisabled();
 for(const name of [/Dish \+ radio/,/Radioisotope power/,/Science booms/]){await page.getByRole('navigation',{name:'Hardware components'}).getByRole('button',{name}).click();await expect.poll(()=>page.locator('.part-poster img').last().evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBeTruthy();}
 await page.getByRole('button',{name:'Separate hardware',exact:true}).click();await page.waitForTimeout(1400);await page.screenshot({path:'docs/qa/voyager-desktop-separated.png'});await page.getByRole('button',{name:'Isolate selection'}).click();await page.getByRole('button',{name:'Show all parts'}).click();
 for(const name of ['Rotate model left','Rotate model right','Zoom in','Zoom out','Reset view'])await page.getByRole('button',{name,exact:true}).click();
 await page.getByRole('button',{name:'FIELD GUIDE',exact:true}).click();await expect(page.getByRole('dialog',{name:'A traveler carrying a world.'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'FIELD GUIDE',exact:true})).toBeFocused();await page.getByRole('button',{name:'Archive discovery',exact:true}).click();
 for(const [id,actions] of [
 ['voyagerSignal',['Aim the schematic beam','Follow the signal to Earth','Let the reply take its time']],
 ['goldenRecord',['Trace the playback diagram','Find the picture instructions','Find the return address']],
 ['paleBlueDot',['Recover the image date','Locate the world in the light','Connect the journeys']],
 ['voyagerMessage',['Open the contents index','Read a human greeting','Save Miso’s final report']],
 ] as const){await scan(page,id);await expect(page.getByRole('button',{name:'Investigation incomplete'})).toBeDisabled();for(const name of actions)await page.getByRole('button',{name,exact:true}).click();await expect.poll(()=>page.locator('.mars-note .photo-window img').evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBeTruthy();await page.screenshot({path:`docs/qa/voyager-desktop-${id}.png`});await page.getByRole('button',{name:'Replay investigation'}).click();await expect(page.getByRole('button',{name:'Investigation incomplete'})).toBeDisabled();for(const name of actions)await page.getByRole('button',{name,exact:true}).click();await page.getByRole('button',{name:'Archive discovery',exact:true}).click();}
 await expect(page.locator('.mars-site-note')).toContainText('5 / 05');await expect(page.locator('.spirit-next-signal')).toContainText('We found more than machines');await page.screenshot({path:'docs/qa/voyager-desktop-complete.png'});
 await page.getByRole('button',{name:'Revisit where we began'}).click();await expect(page.locator('canvas')).toHaveAttribute('data-world','lunar',{timeout:40000});await page.getByRole('button',{name:'Open expedition archive'}).click();await expect(page.locator('.journal')).toContainText('0 of 6 discoveries archived on the Moon');await page.getByRole('button',{name:'Close archive'}).click();await page.locator('.archive-index-trigger').click();await page.getByRole('button',{name:/05.*VOYAGER/}).click();await expect(page.locator('.mars-site-note')).toContainText('5 / 05');await expect(page.locator('canvas')).toHaveAttribute('data-persistent','voyager');expect(errors).toEqual([]);
});
test('Opportunity to Voyager travel pause skip natural and reduced motion',async({page})=>{
 test.setTimeout(90000);await page.goto('/');
 const prepare=()=>page.evaluate(async()=>{const url=performance.getEntriesByType('resource').find(r=>r.name.includes('/src/stores/archive.ts'))!.name;const {useArchive}=await import(/* @vite-ignore */url);const s=useArchive.getState();s.visitChapter('opportunity');for(const id of ['opportunity','opportunityLanding','heatShieldRock','blueberries','purgatory','opportunityLog'])s.discover(id);});
 await prepare();await page.locator('canvas').evaluate(el=>el.setAttribute('data-persistent','travel5'));await page.getByRole('button',{name:'Follow the deep-space signal'}).click();await page.getByRole('button',{name:'Pause journey'}).click();const before=await page.locator('.travel-line i').getAttribute('style');await page.waitForTimeout(300);expect(await page.locator('.travel-line i').getAttribute('style')).toBe(before);await page.getByRole('button',{name:'Resume journey'}).click();await page.getByRole('button',{name:'Skip travel'}).click();await expect(page.locator('canvas')).toHaveAttribute('data-world','voyager',{timeout:40000});
 await prepare();await page.getByRole('button',{name:'Follow the deep-space signal'}).click();await expect(page.getByRole('button',{name:'Approach the distant traveler'})).toBeVisible({timeout:30000});await page.emulateMedia({reducedMotion:'reduce'});await prepare();await page.getByRole('button',{name:'Follow the deep-space signal'}).click();await expect(page.getByRole('button',{name:'Approach the distant traveler'})).toBeVisible();await expect(page.locator('canvas')).toHaveAttribute('data-persistent','travel5');
});
test('Voyager short desktop keyboard exits and lesson scroll reset',async({page})=>{
 await page.setViewportSize({width:1366,height:768});await page.emulateMedia({reducedMotion:'reduce'});await visit(page);await scan(page,'voyager');await page.getByRole('button',{name:/Dish \+ radio/}).click();await page.locator('.part-poster').evaluate(e=>e.scrollTop=e.scrollHeight);await page.getByRole('button',{name:/Radioisotope power/}).click();await expect.poll(()=>page.locator('.part-poster').evaluate(e=>e.scrollTop)).toBe(0);await page.screenshot({path:'docs/qa/voyager-desktop-reduced-short.png'});await page.keyboard.press('Escape');await expect(page.locator('.voyager-dock [data-artifact="voyager"]')).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.reload();await page.locator('.archive-index-trigger').click();await expect(page.getByRole('button',{name:/05.*VOYAGER/})).toBeEnabled();
});

test('Voyager revisits reuse the spacecraft resources and original renderer and camera',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await visit(page);
 await page.evaluate(async()=>{
  const url=performance.getEntriesByType('resource').find(e=>e.name.includes('/@react-three_fiber.js'))!.name;const fiber=await import(/* @vite-ignore */url);const root=fiber._roots.get(document.querySelector('canvas')).store.getState();
  const probe={renderer:root.gl,camera:root.camera,scene:null as any,resources:[] as string[]};(window as any).voyagerProbe=probe;const render=root.gl.render.bind(root.gl);
  root.gl.render=(scene:any,camera:any)=>{if(scene.name==='mersa:voyager'){probe.scene=scene;probe.resources=[];scene.traverse((o:any)=>{if(o.geometry)probe.resources.push(o.geometry.uuid);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])probe.resources.push(m.uuid);});}render(scene,camera);};
 });
 await page.waitForTimeout(150);const before=await page.evaluate(()=>({id:(window as any).voyagerProbe.scene.uuid,resources:(window as any).voyagerProbe.resources}));
 await page.locator('.archive-index-trigger').click();await page.getByRole('button',{name:/OPPORTUNITY/}).click();await expect(page.locator('canvas')).toHaveAttribute('data-world','opportunity',{timeout:30000});await page.locator('.archive-index-trigger').click();await page.getByRole('button',{name:/05.*VOYAGER/}).click();await expect(page.locator('canvas')).toHaveAttribute('data-world','voyager',{timeout:30000});await page.waitForTimeout(150);
 const after=await page.evaluate(async()=>{const p=(window as any).voyagerProbe;const url=performance.getEntriesByType('resource').find(e=>e.name.includes('/@react-three_fiber.js'))!.name;const fiber=await import(/* @vite-ignore */url);const root=fiber._roots.get(document.querySelector('canvas')).store.getState();return {id:p.scene.uuid,resources:p.resources,same:p.renderer===root.gl&&p.camera===root.camera,preparations:performance.getEntriesByName('mersa:prepare:voyager').length};});
 expect(after.id).toBe(before.id);expect(after.resources).toEqual(before.resources);expect(after.same).toBe(true);expect(after.preparations).toBe(1);await expect(page.locator('canvas')).toHaveCount(1);
});
