import { Component, Suspense, lazy, useEffect, useRef, useState, type ReactNode } from 'react';
import gsap from 'gsap';
import { useArchive } from './stores/archive';
import { artifacts, components, type ArtifactId } from './data/archive';
import { initialFlight, type FlightState } from './game/flight';
import { pressControl, clearControls } from './game/input';
const World=lazy(()=>import('./three/World'));
const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
let audio:AudioContext|undefined;
function ping(){if(useArchive.getState().muted)return;audio??=new AudioContext();void audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.setValueAtTime(620,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(260,audio.currentTime+.13);gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.17);}
function Action({children,onClick,disabled=false,className=''}:{children:ReactNode;onClick:()=>void;disabled?:boolean;className?:string}){return <button disabled={disabled} className={`action ${className}`} onClick={()=>{ping();onClick();}}>{children}<span aria-hidden="true">↗</span></button>;}
class WorldBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?<div className="fallback"><p>3D rendering is unavailable on this device.</p><Action onClick={()=>useArchive.getState().setStage('surface')}>Continue with archival evidence</Action></div>:this.props.children;}}
function ScanButton(){const[scanning,setScanning]=useState(false);const ref=useRef<HTMLSpanElement>(null);const setStage=useArchive(s=>s.setStage);useEffect(()=>{if(!scanning)return;const tween=gsap.to(ref.current,{scaleX:1,duration:reduced()?.08:1.4,ease:'none',onComplete:()=>{setStage('signal');ping();}});return()=>{tween.kill();};},[scanning,setStage]);return <button className="scan-action" disabled={scanning} onClick={()=>setScanning(true)}><span ref={ref} className="scan-fill"/><span>{scanning?'RESOLVING SIGNAL':'[ E ]  RESOLVE SIGNAL'}</span><i>+</i></button>;}
function TouchControls(){const hold=(key:string,label:string)=> <button aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);pressControl(key,true);}} onPointerUp={()=>pressControl(key,false)} onPointerCancel={()=>pressControl(key,false)} onLostPointerCapture={()=>pressControl(key,false)}>{label}</button>;return <div className="touch-controls"><div className="d-pad">{hold('KeyW','Forward')}{hold('KeyA','Left')}{hold('KeyS','Back')}{hold('KeyD','Right')}</div>{hold('Space','Brake')}</div>;}
function FlightHUD(){const [flight,setFlight]=useState<FlightState>(initialFlight());const{assist,toggleAssist,retryFlight,flightReset,paused,setPaused}=useArchive();useEffect(()=>{const update=(e:Event)=>setFlight((e as CustomEvent<FlightState>).detail);window.addEventListener('mersa-flight',update);return()=>window.removeEventListener('mersa-flight',update);},[]);useEffect(()=>setFlight(initialFlight()),[flightReset]);const distance=Math.hypot(flight.x,flight.z);const speed=Math.abs(flight.vy);return <section className="flight-hud" aria-label="Flight controls" data-altitude={flight.altitude.toFixed(1)} data-offset={distance.toFixed(1)}>
 <div className="flight-objective"><p className="eyebrow">LUNAR DESCENT / MANUAL CONTROL</p><h1>Find a place to land.</h1><p>Steer into the ring. Brake before touchdown.</p></div>
 <div className="flight-data"><div><small>ALTITUDE / M</small><strong>{Math.round(flight.altitude).toString().padStart(3,'0')}</strong></div><div><small>DESCENT / M·S⁻¹</small><strong className={speed>=3.5?'warning':''}>{speed.toFixed(1)}</strong></div><div><small>TARGET OFFSET / M</small><strong className={distance>6?'':'good'}>{distance.toFixed(1)}</strong></div><div><small>THRUSTER RESERVE</small><strong>{Math.round(flight.fuel)}<em>%</em></strong></div></div>
 <div className="landing-radar" aria-label={`Landing target offset ${distance.toFixed(1)} metres`}><svg viewBox="0 0 150 150" role="img" aria-label="Top view of spacecraft relative to landing ring"><circle cx="75" cy="75" r="60"/><circle cx="75" cy="75" r="18" className="safe-zone"/><path d="M75 0v150M0 75h150"/><circle className="ship-dot" cx={75+Math.max(-58,Math.min(58,flight.x*3))} cy={75+Math.max(-58,Math.min(58,flight.z*3))} r="4"/></svg><small>LZ / 01 — TOP VIEW</small></div>
 <div className="flight-help"><p><kbd>W A S D</kbd> / arrows · steer <kbd>SPACE</kbd> · brake</p><p>Safe: inside ring · descent &lt; 3.5 · drift &lt; 3 m/s</p><div><button className="quiet-button" aria-pressed={assist} onClick={e=>{toggleAssist();e.currentTarget.blur();}}>{assist?'Flight assist on':'Enable flight assist'}</button><button className="quiet-button" onClick={()=>{clearControls();setPaused(!paused);}}>{paused?'Resume flight':'Pause flight'}</button></div></div>
 <TouchControls/>
 {paused&&<div className="flight-message" role="status"><p className="eyebrow">FLIGHT PAUSED</p><h2>Your trajectory is held.</h2><Action onClick={()=>setPaused(false)}>Resume flight</Action></div>}
 {flight.failed&&<div className="flight-message" role="alert"><p className="eyebrow">APPROACH ABORTED / CRAFT RECOVERED</p><h2>{distance>6?'Outside the landing zone.':'Approach speed too high.'}</h2><p>Brake earlier, then settle inside the ring.</p><Action onClick={()=>{retryFlight();setPaused(false);}}>Retry landing</Action></div>}
 {flight.landed&&<div className="landing-success" role="status">CONTACT CONFIRMED / THRUSTERS OFF</div>}
 </section>;}
function Inspector(){const{inspector,inspect,selected,select,inspectedParts,exploded,toggleExploded,isolated,toggleIsolated,resetView,discover}=useArchive();const[angle,setAngle]=useState(19),[pulse,setPulse]=useState(false),[exposure,setExposure]=useState(0);const close=useRef<HTMLButtonElement>(null);useEffect(()=>{close.current?.focus();},[]);useEffect(()=>{if(pulse){const panel=document.querySelector<HTMLElement>('.experiment-panel');if(panel)panel.scrollTop=panel.scrollHeight;}},[pulse]);if(!inspector)return null;const a=artifacts[inspector],part=components.find(c=>c.id===selected)!;const ready=inspector==='eagle'?inspectedParts.length>=3:inspector==='reflector'?pulse:exposure>=90;
 return <section className={`investigation ${inspector}`} role="region" aria-label="Artifact inspection">
 <div className="investigation-title"><p className="eyebrow">{a.code} / SPATIAL ANALYSIS</p><h2>{inspector==='eagle'?'EAGLE / DESCENT STAGE':inspector==='reflector'?'A BRIDGE OF LIGHT':'SOMEONE WAS HERE'}</h2></div><button ref={close} className="exit-inspection" onClick={()=>inspect(null)}>ESC / Return to surface <span>×</span></button>
 {inspector==='eagle'&&<><details className="component-readout" open={window.matchMedia("(min-width:761px)").matches}><summary>Selected part / read evidence</summary><p className="eyebrow">{part.material}</p><p>{part.fact}</p><small>NASA / Michael D. Carbajal · adapted descent-stage reconstruction</small></details><nav className="component-switch" aria-label="Hardware components">{components.map((c,i)=><button key={c.id} aria-pressed={selected===c.id} onClick={()=>select(c.id)}><span>{String(i+1).padStart(2,'0')}</span>{c.id==='structure'?'Structure':c.id==='engine'?'Engine':'Landing gear'}<small>{inspectedParts.includes(c.id)?'✓':'+'}</small></button>)}</nav><details className="model-tools" open={window.matchMedia("(min-width:761px)").matches}><summary>Manipulate hardware</summary><div className="tool-buttons"><button aria-pressed={exploded} onClick={toggleExploded}>{exploded?'Assemble':'Separate'} hardware</button><button aria-pressed={isolated} onClick={toggleIsolated}>{isolated?'Show all parts':'Isolate selection'}</button><button onClick={resetView}>Reset view</button><button aria-label="Rotate model left" onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'left'}))}>↶</button><button aria-label="Rotate model right" onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'right'}))}>↷</button><button aria-label="Zoom in" onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'in'}))}>+</button><button aria-label="Zoom out" onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'out'}))}>−</button></div></details><p className="orbit-hint">DRAG THE HARDWARE TO ORBIT · WHEEL TO ZOOM</p></>}
 {inspector==='reflector'&&<div className="experiment-panel"><p>A hundred prisms. No power source.<br/>Send a pulse from the world they came from.</p><svg className={`laser ${pulse?'returned':''}`} viewBox="0 0 320 95" role="img" aria-label={pulse?'Laser return detected':'Align laser to reflector'}><circle cx="24" cy="42" r="15"/><path d="M286 22v40m0-20h15"/><path className="beam" d={`M40 42L286 ${42+angle}`}/>{pulse&&<path className="beam return" d="M286 48L40 48"/>}<text x="4" y="86">EARTH</text><text x="245" y="86">ARRAY</text></svg><label htmlFor="beam">Beam alignment <span>{angle}°</span></label><input id="beam" type="range" min="-25" max="25" value={angle} onChange={e=>{setAngle(+e.target.value);setPulse(false);}}/><p className="hint">Align to 0° to intersect the array.</p><Action disabled={Math.abs(angle)>1} onClick={()=>setPulse(true)}>Transmit pulse</Action>{pulse&&<p className="discovery-result" role="status">RETURN DETECTED<br/>Distance = light speed × round-trip time ÷ 2.</p>}<small>Illustrative light path; not to scale.</small></div>}
 {inspector==='footprints'&&<><figure className="evidence-photo"><img src="/textures/apollo11-bootprint.jpg" alt="NASA photograph of a bootprint impressed into lunar regolith" style={{filter:`brightness(${.2+exposure*.008}) contrast(${1.4-exposure*.004})`}}/><figcaption>NASA / EDWIN “BUZZ” ALDRIN · APOLLO 11, 1969</figcaption></figure><div className="experiment-panel footprint-panel"><p>Not a wheel. Not a machine.<br/>Recover the pattern in the dust.</p><label htmlFor="exposure">Evidence exposure <span>{exposure}%</span></label><input id="exposure" type="range" min="0" max="100" value={exposure} onChange={e=>setExposure(+e.target.value)}/>{exposure>=90&&<p className="discovery-result" role="status">BIOLOGICAL PRESENCE<br/>A protective boot. A living explorer.</p>}</div></>}
 {ready&&<details className="interpretation"><summary>Field note & NASA source</summary><p>{inspector==='eagle'?a.interpretation:a.purpose}</p><a href={a.source} target="_blank" rel="noreferrer">NASA source ↗</a></details>}
 <div className="archive-action"><Action disabled={!ready} onClick={()=>{discover(inspector);inspect(null);}}>{ready?'Archive discovery':inspector==='eagle'?`Inspect all parts / ${inspectedParts.length} of 3`:'Investigation incomplete'}</Action></div>
 </section>;}
function Journal({close}:{close:()=>void}){const{discovered}=useArchive();const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=dialog.current;el?.showModal();return()=>el?.close();},[]);return <dialog className="journal" ref={dialog} onCancel={e=>{e.preventDefault();close();}}><button className="quiet-button close-journal" onClick={close}>Close archive ×</button><p className="eyebrow">MERSA / EXPEDITION ARCHIVE</p><h2>Evidence of a species.</h2><p>{discovered.length} of 3 discoveries archived.</p>{discovered.map(id=><article key={id}><h3>{artifacts[id].name}</h3><p>{artifacts[id].interpretation}</p><a href={artifacts[id].source} target="_blank" rel="noreferrer">Verified NASA source ↗</a></article>)}{!discovered.length&&<p>No records yet. Follow the signal to the surface.</p>}<details><summary>Imagery, reconstruction & credits</summary><p>A fictional alien expedition through real human history. The ship, landing handling, holographic separation and archive confidence are storytelling devices. The scene is not an exact archaeological survey.</p><ul><li><a href="https://svs.gsfc.nasa.gov/4720/" target="_blank" rel="noreferrer">Moon map: NASA SVS</a></li><li><a href="https://apod.nasa.gov/apod/ap180721.html" target="_blank" rel="noreferrer">Lunar panorama: Neil Armstrong / Apollo 11 / NASA</a></li><li><a href="https://science.nasa.gov/3d-resources/apollo-lunar-module/" target="_blank" rel="noreferrer">Lunar module model: NASA / Michael D. Carbajal</a></li><li><a href="https://svs.gsfc.nasa.gov/3895/" target="_blank" rel="noreferrer">Star map: NASA/Goddard SVS / Ernie Wright</a></li><li><a href="https://science.nasa.gov/resource/mars-planet-globe/" target="_blank" rel="noreferrer">Mars globe: NASA/JPL-Caltech, Viking mosaic</a></li></ul></details></dialog>;}
export default function App(){const{stage,setStage,inspector,inspect,discovered,muted,toggleMute,restart,setPaused}=useArchive();const[log,setLog]=useState(false);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code==='Escape'&&inspector)inspect(null);if(e.code==='KeyE'&&stage==='entry')document.querySelector<HTMLButtonElement>('.scan-action')?.click();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[stage,inspector,inspect]);useEffect(()=>{if(stage==='approach')document.activeElement instanceof HTMLElement&&document.activeElement.blur();},[stage]);const done=discovered.length===3;const openLog=()=>{clearControls();setPaused(true);setLog(true);};return <main className={`experience stage-${stage} ${inspector?'inspecting':''}`}>
 <WorldBoundary><Suspense fallback={<div className="world-loading">RESOLVING WORLD DATA…</div>}><World/></Suspense></WorldBoundary><div className="edge-shade"/><div className="grain" aria-hidden="true"/>
 <header className="hud"><button className="wordmark" onClick={openLog} aria-label="Open expedition archive">MERSA<span>INTERSTELLAR FIELD ARCHIVE</span></button><div className="chapter-track"><span className={['entry','signal','approach'].includes(stage)?'active':''}>01 / ARRIVAL</span><i/><span className={['surface','identified','explore'].includes(stage)?'active':''}>02 / EVIDENCE</span><i/><span className={stage==='complete'?'active':''}>03 / BEYOND</span></div><div className="header-actions"><button onClick={()=>{toggleMute();ping();}} aria-label={muted?'Enable audio':'Mute audio'}>{muted?'SOUND OFF':'SOUND ON'}</button><button onClick={openLog}>ARCHIVE <b>{String(discovered.length).padStart(2,'0')}</b></button></div></header>
 {!inspector&&<>
 {(stage==='entry'||stage==='signal')&&<section className="orbital-hud"><div className="orbit-caption"><p className="eyebrow">SOL SYSTEM / SATELLITE OF PLANET 03</p><h1>{stage==='entry'?'Investigate the surface signal.':'Earth’s Moon.'}</h1><p>{stage==='entry'?'Artificial origin. No response.':'The signature is on the surface. Take the craft down.'}</p></div><div className="orbital-target"><span className="reticle"/><small>{stage==='entry'?'UNIDENTIFIED SURFACE SIGNAL':'SIGNAL LOCK / LUNAR SURFACE'}</small></div><div className="orbit-side"><p>OBJECT / 03.1</p><span>NO ACTIVE RESPONSE</span><i/><p>OBSERVER / KSHAT-RA</p><span>EXPLORATION CRAFT / READY</span></div><div className="orbit-action">{stage==='entry'?<ScanButton/>:<Action onClick={()=>{clearControls();setStage('approach');}}>Take flight controls</Action>}<p><kbd>W A S D</kbd> moves your survey craft · sound is optional</p></div></section>}
 {stage==='approach'&&<FlightHUD/>}
 {stage==='surface'&&<section className="surface-objective"><p className="eyebrow">LANDED / THRUSTERS OFF</p><h1>Something was here before us.</h1><p>Metallic geometry. No active power.</p><Action onClick={()=>setStage('identified')}>Scan the unknown hardware</Action></section>}
 {stage==='identified'&&<section className="identification"><p className="eyebrow">ORIGIN RESOLVED / HUMAN</p><h1>APOLLO 11</h1><p>EAGLE · DESCENT STAGE · 20 JULY 1969</p><p className="reveal-line">Two living beings crossed the emptiness.<br/>This is what stayed behind.</p><Action onClick={()=>setStage('explore')}>Approach the hardware</Action></section>}
 {stage==='explore'&&<><div className="site-caption"><p className="eyebrow">TRANQUILITY BASE / THREE TRACES</p><h1>Read what they left behind.</h1><p>Click the hardware to separate its parts.</p></div><nav className="discovery-dock" aria-label="Surface discoveries">{(['eagle','reflector','footprints'] as ArtifactId[]).map((id,i)=><button key={id} data-artifact={id} onClick={()=>inspect(id)}><span>{discovered.includes(id)?'✓':String(i+1).padStart(2,'0')}</span><strong>{id==='eagle'?'Eagle':id==='reflector'?'Reflective array':'Surface traces'}</strong><small>{discovered.includes(id)?'ARCHIVED':'INVESTIGATE ↗'}</small></button>)}</nav>{done&&<div className="next-signal"><p>NEW SIGNAL / BEYOND THIS WORLD</p><Action onClick={()=>setStage('complete')}>Listen beyond the Moon</Action></div>}</>}
 {stage==='complete'&&<section className="mars-ending"><img src="/textures/mars-globe-2k.jpg" alt="NASA Viking mosaic of Mars with Valles Marineris"/><div className="mars-copy"><p className="eyebrow">LUNAR ARCHIVE COMPLETE / NEW SIGNAL</p><h1>MARS</h1><p>They did not stop at the Moon.</p><blockquote>{artifacts.footprints.interpretation}</blockquote><Action onClick={openLog}>Read the expedition archive</Action><button className="quiet-button" onClick={()=>setStage('explore')}>Return to the Moon</button><button className="quiet-button" onClick={restart}>Restart expedition</button></div><span className="mars-credit">NASA / JPL-CALTECH · VIKING MOSAIC<br/>NEXT CHAPTER / NOT YET EXPLORED</span></section>}
 <footer className="world-footer"><span>{stage==='complete'?'THE ARCHIVE CONTINUES':stage==='entry'||stage==='signal'?'NASA SVS LUNAR MAP / STAR CATALOG':'NASA APOLLO 11 IMAGERY / RECONSTRUCTED SCENE'}</span><div><span>HUMAN MODEL</span><b>{String(2+discovered.length*4).padStart(2,'0')}%</b></div></footer>
 </>}{inspector&&<Inspector key={inspector}/>}{log&&<Journal close={()=>{setLog(false);setPaused(false);}}/>}
 </main>;}