import { Component, lazy, Suspense, useEffect, useRef, useState, type ReactNode } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useArchive } from './stores/archive';
import { artifacts, components, type ArtifactId } from './data/archive';
const World=lazy(()=>import('./three/World'));
gsap.registerPlugin(ScrollTrigger);
const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
let audio:AudioContext|undefined;
function ping(){if(useArchive.getState().muted)return;audio??=new AudioContext();void audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(540,audio.currentTime);o.frequency.exponentialRampToValueAtTime(280,audio.currentTime+.14);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.2);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.21);}
class WorldBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?<div className="world-fallback"><p>3D rendering unavailable. All discoveries remain accessible through the archive controls.</p></div>:this.props.children;}}
function Button({children,onClick,disabled=false,secondary=false,...props}:{children:ReactNode;onClick:()=>void;disabled?:boolean;secondary?:boolean;'aria-label'?:string}){return <button className={secondary?'button secondary':'button'} onClick={()=>{ping();onClick();}} disabled={disabled} {...props}>{children}<span aria-hidden="true">&#8599;</span></button>;}
function Scan({onDone,label='Scan structure'}:{onDone:()=>void;label?:string}){const[scanning,setScanning]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);useEffect(()=>()=>clearTimeout(timer.current),[]);return <><Button disabled={scanning} onClick={()=>{setScanning(true);timer.current=setTimeout(()=>{onDone();ping();},reduced()?100:1700);}}>{scanning?'Resolving material signature…':label}</Button>{scanning&&<div className="scan-progress" role="status"><span/>Analysis in progress</div>}</>;}
function Inspector(){
 const {inspector,inspect,discover,discovered,selected,select,exploded,toggleExploded,isolated,toggleIsolated,resetView}=useArchive();
 const [seen,setSeen]=useState<string[]>([]),[angle,setAngle]=useState(22),[fired,setFired]=useState(false),[exposure,setExposure]=useState(0),[evidence,setEvidence]=useState(false);
 const panel=useRef<HTMLDivElement>(null);const close=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!inspector)return;const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')inspect(null);if(e.key==='Tab'){const nodes=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a,input');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus();};},[inspector,inspect]);
 useEffect(()=>{if(inspector==='eagle')setSeen(s=>s.includes(selected)?s:[...s,selected]);},[selected,inspector]);
 if(!inspector)return null;const a=artifacts[inspector];const ready=inspector==='eagle'?seen.length===3:inspector==='reflector'?fired:evidence;const saved=discovered.includes(inspector);
 return <div className={`inspection ${inspector}`} role="dialog" aria-modal="true" aria-labelledby="inspection-title" ref={panel}>
 <div className="inspection-top"><span className="eyebrow">{a.code} / ISOLATED INVESTIGATION</span><button className="text-button" ref={close} onClick={()=>inspect(null)}>Close investigation <span>×</span></button></div>
 {inspector!=='footprints'&&<div className="model-caption"><span className="cross">+</span> SCHEMATIC RECONSTRUCTION <br/><small>Drag to orbit · scroll to zoom</small></div>}
 <section className="inspection-panel"><p className="eyebrow">{a.subtitle}</p><h2 id="inspection-title">{a.name}</h2>
 {inspector==='eagle'&&<><p>Read the machine, one component at a time.</p><div className="component-list">{components.map(c=><button key={c.id} className={selected===c.id?'selected':''} onClick={()=>select(c.id)}>{c.name}<span>{seen.includes(c.id)?'\u2713':'+'}</span></button>)}</div><div className="component-fact" aria-live="polite"><span className="eyebrow">{components.find(c=>c.id===selected)?.material}</span><p>{components.find(c=>c.id===selected)?.fact}</p></div><div className="tools"><button onClick={toggleExploded} aria-pressed={exploded}>{exploded?'Assemble':'Explode'} parts</button><button onClick={toggleIsolated} aria-pressed={isolated}>{isolated?'Show all':'Isolate part'}</button><button onClick={resetView}>Reset view</button></div><div className="tools view-tools"><button onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'left'}))} aria-label="Rotate model left">&#8630; Rotate</button><button onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'right'}))} aria-label="Rotate model right">Rotate &#8631;</button><button onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'in'}))} aria-label="Zoom in">+</button><button onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'out'}))} aria-label="Zoom out">-</button></div></>}
 {inspector==='reflector'&&<><p>A silent device. No power source. What could these mirrors be waiting for?</p><svg className={`laser-diagram ${fired?'returned':''}`} viewBox="0 0 340 115" aria-label={fired?'A laser pulse travels from Earth to the array and returns.':'Align a laser from Earth with the lunar array.'} role="img"><circle cx="28" cy="57" r="16"/><path d="M300 38v38m0-19h15"/><path className="beam" d={`M45 57 L298 ${57+angle*1.2}`}/>{fired&&<path className="return" d="M298 63L45 63"/>}<text x="8" y="103">EARTH</text><text x="260" y="103">ARRAY</text></svg><label htmlFor="angle">Beam alignment <span>{angle}°</span></label><input id="angle" type="range" min="-30" max="30" value={angle} onChange={e=>{setAngle(+e.target.value);setFired(false);}}/><p className="hint" aria-live="polite">{Math.abs(angle)<=2?'Target acquired. Send a pulse.':'Adjust to 0° to intersect the array.'}</p><Button disabled={Math.abs(angle)>2} onClick={()=>{setFired(true);ping();}}>Send laser pulse</Button>{fired&&<p className="success" role="status">RETURN DETECTED / Distance = light speed × round-trip time ÷ 2.</p>}<small>Diagram is illustrative; angles and distances are not to scale.</small></>}
 {inspector==='footprints'&&<><p>Regular ridges. Repeated pressure. Something moved across this surface.</p><label htmlFor="exposure">Reconstruction exposure <span>{exposure}%</span></label><input id="exposure" type="range" min="0" max="100" value={exposure} onChange={e=>{setExposure(+e.target.value);if(+e.target.value>=90)setEvidence(true);}}/><p className="hint">Raise exposure to recover the surface pattern.</p>{evidence&&<p className="success" role="status">PATTERN MATCH / A protective boot, worn by a living explorer.</p>}</>}
 {ready&&<div className="discovery-copy"><p>{a.purpose}</p><blockquote>{a.interpretation}</blockquote><a href={a.source} target="_blank" rel="noreferrer">{a.sourceName} &#8599;</a></div>}
 <Button disabled={!ready} onClick={()=>{discover(inspector);inspect(null);}}>{saved?'Return to the surface':ready?'Add discovery to archive':'Investigation incomplete'}</Button>
 </section>
 {inspector==='footprints'&&<figure className="footprint-figure"><img src="/textures/apollo11-bootprint.jpg" alt="Buzz Aldrin’s archival photograph of a treaded bootprint pressed into lunar soil" style={{filter:`brightness(${.12+exposure*.0088}) contrast(${1.9-exposure*.008})`}}/><figcaption>AS11 / HUMAN TRACE<br/>NASA · Edwin “Buzz” Aldrin · 1969<br/><span>Archival evidence, recovered by the explorer</span></figcaption></figure>}
 </div>;
}
function ArchiveLog({close}:{close:()=>void}){const{discovered}=useArchive();const box=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';const trap=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=box.current?.querySelectorAll<HTMLElement>('button,a');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',trap);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',trap);previous?.focus();};},[close]);return <div ref={box} className="log-backdrop"><section className="archive-log" role="dialog" aria-modal="true" aria-labelledby="log-title" onKeyDown={e=>{if(e.key==='Escape')close();}}><button autoFocus className="text-button" onClick={close}>Close archive ×</button><p className="eyebrow">MERSA / FIELD NOTES</p><h2 id="log-title">The story so far.</h2><p>{discovered.length} of 3 discoveries archived.</p>{discovered.map(id=><article key={id}><p className="eyebrow">{artifacts[id].code}</p><h3>{artifacts[id].name}</h3><p>{artifacts[id].interpretation}</p></article>)}{!discovered.length&&<p>There is no record yet. Follow the signal.</p>}<p className="fineprint">A fictional future encounter with real human history. Landscapes and 3D objects are schematic reconstructions. Archive confidence is a narrative indicator.</p></section></div>;}
export default function App(){
 const {stage,setStage,progress,setProgress,inspector,inspect,discovered,muted,toggleMute,restart}=useArchive();const[alignment,setAlignment]=useState(-24),[log,setLog]=useState(false);const approach=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(stage!=='approach')return;window.scrollTo(0,0);const trigger=ScrollTrigger.create({trigger:approach.current,start:'top top',end:'bottom bottom',onUpdate:s=>setProgress(s.progress)});return()=>trigger.kill();},[stage,setProgress]);
 useEffect(()=>{if(stage!=='approach')window.scrollTo(0,0);},[stage]);
 const lunar=['surface','identified','explore','complete'].includes(stage);const done=discovered.length===3;
 return <main className={lunar?'experience lunar':'experience cosmic'}>
 <WorldBoundary><Suspense fallback={<div className="loading-world">Resolving star field…</div>}><World/></Suspense></WorldBoundary><div className="vignette"/><div className="grain" aria-hidden="true"/>
 <header className="hud"><a className="brand" href="#" onClick={e=>{e.preventDefault();setLog(true);}} aria-label="Open MERSA archive"><span className="brand-mark">M</span><span>MERSA<small>THE HUMAN TRACE</small></span></a><div className="mission-label"><span className="status-dot"/>{lunar?'EXPEDITION 01 / LUNAR ARCHIVE':'EXPEDITION 00 / SYSTEM ENTRY'}</div><div className="header-actions"><button className="icon-button" onClick={()=>{toggleMute();ping();}} aria-label={muted?'Enable audio':'Mute audio'}>{muted?'SOUND OFF':'SOUND ON'}<span aria-hidden="true">{muted?'\u223f':'\u224b'}</span></button><button className="icon-button" onClick={()=>setLog(true)}>ARCHIVE <span>{String(discovered.length).padStart(2,'0')}</span></button></div></header>
 {!inspector&&<>
 {(stage==='entry'||stage==='signal')&&<section className="entry-content"><p className="eyebrow"><span className="cross">+</span> ORION ARM / UNCATALOGUED SYSTEM</p><h1>{stage==='entry'?<>Nothing here<br/>is quite <em>silent.</em></>:<>A trace.<br/>Beyond <em>home.</em></>}</h1><p className="intro">{stage==='entry'?'Eight worlds orbit a solitary star. Between the noise, something that nature did not make.':'An artificial signature on the satellite of the third planet. No response. Only evidence.'}</p><dl className="telemetry"><div><dt>STAR DESIGNATION</dt><dd>SOL</dd></div><div><dt>{stage==='entry'?'ARTIFICIAL SIGNALS':'SIGNAL ORIGIN'}</dt><dd>{stage==='entry'?'MULTIPLE / UNRESOLVED':"EARTH’S MOON"}</dd></div><div><dt>CLASSIFICATION</dt><dd className="accent">{stage==='entry'?'UNKNOWN':'SURFACE ANOMALY'}</dd></div></dl>{stage==='entry'?<Scan label="Focus on primary signal" onDone={()=>setStage('signal')}/>:<Button onClick={()=>setStage('approach')}>Follow the signal</Button>}<p className="subnote">YOU ARE THE EXPLORER. HUMANITY IS THE MYSTERY.</p></section>}
 {(stage==='entry'||stage==='signal')&&<div className="signal-marker" aria-hidden="true"><span className="target-ring"/><div className="leader"/><p>{stage==='entry'?'SIGNAL 01 / UNKNOWN ORIGIN':'SIGNAL 01 / EARTH’S MOON'}<br/><span>ARTIFICIAL SIGNATURE DETECTED</span></p></div>}
 {stage==='approach'&&<div className="approach-scroll" ref={approach}><section className="approach-content"><p className="eyebrow">01 / APPROACH VECTOR</p><h1>Into the<br/><em>stillness.</em></h1><p>Follow the signal down to the surface.</p><div className="approach-meter"><span style={{width:`${progress*100}%`}}/></div><p className="eyebrow">DESCENT CORRIDOR / {Math.round(progress*100)}%</p>{progress<.85?<><p className="scroll-cue">Scroll to approach</p><button className="text-button" onClick={()=>window.scrollTo({top:document.documentElement.scrollHeight,behavior:reduced()?'instant':'smooth'})}>Use assisted approach &#8599;</button></>:<div className="landing-controls"><label htmlFor="landing">Align descent vector <span>{alignment}°</span></label><input id="landing" type="range" min="-30" max="30" value={alignment} onChange={e=>setAlignment(+e.target.value)}/><p className="hint">{Math.abs(alignment)<=3?'Stable corridor acquired.':'Center the vector at 0°.'}</p><Button disabled={Math.abs(alignment)>3} onClick={()=>setStage('surface')}>Begin surface approach</Button></div>}</section></div>}
 {stage==='surface'&&<><section className="surface-copy"><p className="eyebrow">SURFACE CONTACT / SATELLITE 03.1</p><h1>We were not<br/><em>the first.</em></h1><p>A geometry the landscape cannot explain.</p><div className="spec-line">METALLIC COMPOSITION<br/>NO ACTIVE POWER<br/>ORIGIN UNKNOWN</div><Scan onDone={()=>setStage('identified')}/></section><div className="artifact-callout"><span className="target-ring"/><p>ARTIFICIAL STRUCTURE<br/><span>CLASSIFICATION PENDING</span></p></div></>}
 {stage==='identified'&&<section className="reveal"><p className="eyebrow">IDENTITY RESOLVED / HUMAN ORIGIN</p><h1>Apollo <em>11.</em></h1><p className="location">TRANQUILITY BASE · EARTH’S MOON</p><p>They crossed the void.<br/>And left a way to remember.</p><Button onClick={()=>setStage('explore')}>Investigate the site</Button><span className="date-label">FIRST HUMAN LANDING / 20 JULY 1969</span></section>}
 {stage==='explore'&&<><section className="explore-heading"><p className="eyebrow">CHAPTER 01 / TRANQUILITY BASE</p><h1>The things<br/>they <em>left.</em></h1><p>Three traces. One species.<br/>Choose an anomaly to investigate.</p></section><nav className="site-discoveries" aria-label="Surface discoveries">{(['eagle','reflector','footprints'] as ArtifactId[]).map((id,i)=><button key={id} data-artifact={id} onClick={()=>inspect(id)} className={discovered.includes(id)?'found':''}><span className="discovery-number">0{i+1}</span><span><small>{discovered.includes(id)?'ARCHIVED':'ANOMALY DETECTED'}</small>{discovered.includes(id)?artifacts[id].name:artifacts[id].unknownName}</span><span className="discovery-arrow">{discovered.includes(id)?'\u2713':'\u2197'}</span></button>)}</nav><div className="surface-note">SCHEMATIC SITE RECONSTRUCTION<br/>EXPLORATION ZONE / TRANQUILITY <span>01</span></div>{done&&<div className="next-signal"><p className="eyebrow">HUMAN MODEL UPDATED / NEW SIGNAL AVAILABLE</p><Button onClick={()=>setStage('complete')}>Listen beyond the Moon</Button></div>}</>}
 {stage==='complete'&&<section className="ending"><p className="eyebrow">LUNAR ARCHIVE / COMPLETE</p><h1>They did not<br/><em>stop here.</em></h1><blockquote>Capable of leaving their home.<br/>Curious enough to keep going.</blockquote><div className="mars-signal"><span className="status-dot"/><span>NEW SIGNAL DETECTED<strong>MARS</strong><small>CHAPTER 02 / AWAITS EXPLORATION</small></span></div><Button onClick={()=>setLog(true)}>Read the archive</Button><button className="text-button" onClick={()=>setStage('explore')}>Return to Tranquility Base &#8599;</button><button className="text-button restart" onClick={()=>{restart();setAlignment(-24);}}>Restart expedition</button></section>}
 <footer className="footer"><div><span className="eyebrow">{lunar?'OBSERVER / KSHAT-RA':'DEEP SPACE / FIELD RECORD 001'}</span><p>{lunar?'A world without wind. A story without a voice.':'No known origin. No prior contact.'}</p></div><div className="confidence"><span className="eyebrow">HUMAN MODEL / {String(2+discovered.length*4).padStart(2,'0')}%</span><div>{Array.from({length:20},(_,i)=><i key={i} className={i<2+discovered.length*4?'lit':''}/>)}</div></div><span className="page-code">{stage==='complete'?'01 / END':lunar?'01 / 05':'00 / 05'}</span></footer>
 </>}
 {inspector&&<Inspector key={inspector}/>}{log&&<ArchiveLog close={()=>setLog(false)}/>}
 </main>;
}

