import { OpportunitySurface, OpportunityInspector, OpportunityTravelHUD } from './OpportunityChapter';
import { isOpportunityArtifact } from './data/opportunity';
import { useShallow } from 'zustand/react/shallow';
import { SpiritSurface, SpiritInspector, SpiritTravelHUD } from './SpiritChapter';
import { isSpiritArtifact } from './data/spirit';
import { ArchiveIndex, LunarSignal, TravelHUD, MarsSurface, MarsInspector } from './MarsChapter';
import { isMarsArtifact } from './data/mars';
import { Component, Suspense, lazy, useEffect, useRef, useState, type ReactNode } from 'react';
import { Arrival, Cockpit, WalkPrompt, CatQuestion } from './Journey';
import { useArchive } from './stores/archive';
import { artifacts, components, type ArtifactId } from './data/archive';
import FlightHUD from './FlightHUD';
import PartPoster from './PartPoster';
import Learning from './Learning';
import ClueIcon from './ClueIcon';
import SeismicExhibit from './SeismicExhibit';
import ExpeditionLog from './ExpeditionLog';
import { MissionAudio, SoundClip } from './MissionAudio';
import { clearControls } from './game/input';
const World=lazy(()=>import('./three/World'));

let audio:AudioContext|undefined;
function ping(){if(useArchive.getState().muted)return;audio??=new AudioContext();void audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.setValueAtTime(620,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(260,audio.currentTime+.13);gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.17);}
function Action({children,onClick,disabled=false,className=''}:{children:ReactNode;onClick:()=>void;disabled?:boolean;className?:string}){return <button disabled={disabled} className={`action ${className}`} onClick={()=>{ping();onClick();}}>{children}<span aria-hidden="true">↗</span></button>;}
class WorldBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?<div className="fallback"><p>3D rendering is unavailable on this device.</p><Action onClick={()=>useArchive.getState().setStage('surface')}>Continue with archival evidence</Action></div>:this.props.children;}}
function Inspector(){const id=useArchive(s=>s.inspector);return isOpportunityArtifact(id)?<OpportunityInspector key={id} id={id}/>:isSpiritArtifact(id)?<SpiritInspector id={id}/>:isMarsArtifact(id)?<MarsInspector id={id}/>:<ApolloInspector/>;}
function ApolloInspector(){const{inspector,inspect,selected,select,inspectedParts,exploded,toggleExploded,isolated,toggleIsolated,resetView,discover}=useArchive(useShallow(s=>({inspector:s.inspector,inspect:s.inspect,selected:s.selected,select:s.select,inspectedParts:s.inspectedParts,exploded:s.exploded,toggleExploded:s.toggleExploded,isolated:s.isolated,toggleIsolated:s.toggleIsolated,resetView:s.resetView,discover:s.discover})));const[revealed,setRevealed]=useState(false);const {cutaway,toggleCutaway,historical,toggleHistorical}=useArchive(useShallow(s=>({cutaway:s.cutaway,toggleCutaway:s.toggleCutaway,historical:s.historical,toggleHistorical:s.toggleHistorical})));const[angle,setAngle]=useState(19),[pulse,setPulse]=useState(false);const close=useRef<HTMLButtonElement>(null);useEffect(()=>{close.current?.focus();},[]);useEffect(()=>{if(pulse){const panel=document.querySelector<HTMLElement>('.experiment-panel');if(panel)panel.scrollTop=panel.scrollHeight;}},[pulse]);if(!inspector)return null;const a=artifacts[inspector];const ready=inspector==='eagle'?inspectedParts.length>=3:inspector==='reflector'?pulse:inspector==='footprints'?true:revealed;
 return <section className={`investigation ${inspector}`} role="region" aria-label="Artifact inspection">
 <div className="investigation-title"><p className="eyebrow">{a.code} / SPATIAL ANALYSIS</p><h2>{a.name}</h2></div><button ref={close} className="exit-inspection" onClick={()=>inspect(null)}>ESC / Return to surface <span>×</span></button>
 {inspector==='eagle'&&<>{selected&&<PartPoster part={selected} conclusion={ready?a.interpretation:undefined}/>}<div className="cutaway-controls"><p className="inspection-invitation">Pick a part. Watch it float out. Tap again to return.</p><button aria-pressed={cutaway} onClick={toggleCutaway}>{cutaway?"Close cross-section":"Open cross-section"}</button><button aria-pressed={historical} onClick={toggleHistorical}>{historical?"See what remains today":"See the complete Eagle"}</button><button className="separate-primary" aria-pressed={exploded} onClick={toggleExploded}>{exploded?"Assemble":"Separate"} hardware</button><small>{historical?"Historical reconstruction / before liftoff":"Descent stage / left on the Moon"}</small></div><nav className="component-switch" aria-label="Hardware components">{components.map((c,i)=><button key={c.id} aria-pressed={selected===c.id} onClick={()=>select(c.id)}><span>{String(i+1).padStart(2,'0')}</span>{c.id==='structure'?'Structure':c.id==='engine'?'Engine':'Landing gear'}<small>{selected===c.id?'✓':'+'}</small></button>)}</nav><details className="model-tools" ><summary>More model controls</summary><div className="tool-buttons"><button disabled={!selected} aria-pressed={isolated} onClick={toggleIsolated}>{isolated?'Show all parts':'Isolate selection'}</button><button onClick={resetView}>Reset view</button><button aria-label="Rotate model left" onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'left'}))}>↶</button><button aria-label="Rotate model right" onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'right'}))}>↷</button><button aria-label="Zoom in" onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'in'}))}>+</button><button aria-label="Zoom out" onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:'out'}))}>−</button></div></details><p className="orbit-hint">Drag to explore every angle / Scroll to look closer</p></>}
 {inspector==='reflector'&&<PartPoster part="reflector" conclusion={ready?a.interpretation:undefined}/>}
 {inspector==='reflector'&&<div className="experiment-panel"><p>A hundred prisms. No power source.<br/>Send a pulse from the world they came from.</p><svg className={`laser ${pulse?'returned':''}`} viewBox="0 0 320 95" role="img" aria-label={pulse?'Laser return detected':'Align laser to reflector'}><circle cx="24" cy="42" r="15"/><path d="M286 22v40m0-20h15"/><path className="beam" d={`M40 42L286 ${42+angle}`}/>{pulse&&<path className="beam return" d="M286 48L40 48"/>}<text x="4" y="86">EARTH</text><text x="245" y="86">ARRAY</text></svg><label htmlFor="beam">Beam alignment <span>{angle}°</span></label><input id="beam" type="range" min="-25" max="25" value={angle} onChange={e=>{setAngle(+e.target.value);setPulse(false);}}/><p className="hint">Align to 0° to intersect the array.</p><Action disabled={Math.abs(angle)>1} onClick={()=>setPulse(true)}>Transmit pulse</Action>{pulse&&<p className="discovery-result" role="status">RETURN DETECTED<br/>Distance = light speed × round-trip time ÷ 2.</p>}<small>Illustrative light path; not to scale.</small></div>}
 {inspector==='footprints'&&<><figure className="evidence-photo"><img src="/textures/apollo11-bootprint.jpg" alt="NASA photograph of a bootprint impressed into lunar regolith"/><figcaption>NASA / EDWIN “BUZZ” ALDRIN · APOLLO 11, 1969</figcaption></figure><div className="experiment-panel footprint-panel"><p>Look at the ridges in the dust.<br/>They match the sole of an astronaut’s boot.</p><p className="evidence-conclusion"><small>ALIEN INTERPRETATION</small>{a.interpretation}</p><SoundClip kind="step"/></div></>}
 {['camera','messages'].includes(inspector)&&<div className="mini-investigation"><p className="eyebrow">{revealed?a.subtitle:a.unknownName}</p><svg viewBox="0 0 320 150" aria-label={inspector==='camera'?'Schematic light transmission':inspector==='seismometer'?'Illustrative seismic trace':'Schematic engraved message'} role="img">{inspector==='camera'?<><rect x="28" y="52" width="65" height="46"/><path d="M93 63l30-15v55L93 88M133 74h130M242 60l21 14-21 14"/><circle cx="283" cy="74" r="15"/></>:inspector==='seismometer'?<path className={revealed?'trace-active':''} d="M10 80h60l10-12 12 30 13-66 15 100 14-83 15 41 12-15h149"/>:<><rect x="25" y="35" width="155" height="86" rx="3"/><path d="M40 55h123M40 73h123M40 91h90"/><circle cx="244" cy="78" r="43"/><circle cx="244" cy="78" r="8"/></>}</svg><small>Schematic learning illustration</small><button className="action" onClick={()=>setRevealed(true)}>{inspector==='camera'?'Follow the signal':inspector==='seismometer'?'Listen for moonquakes':'Read the message'} <span aria-hidden="true">&rarr;</span></button>{revealed&&<p role="status">{a.purpose}</p>}</div>}
 {inspector==='seismometer'&&<SeismicExhibit revealed={revealed} reveal={()=>setRevealed(true)}/>}
 {ready&&inspector!=='eagle'&&inspector!=='reflector'&&inspector!=='footprints'&&<p className="evidence-conclusion"><small>ALIEN INTERPRETATION</small>{a.interpretation}</p>}
 {ready&&<details className="interpretation"><summary>Field note & NASA source</summary><p>{inspector==='eagle'?a.interpretation:a.purpose}</p><a href={a.source} target="_blank" rel="noreferrer">NASA source ↗</a></details>}
 <div className="archive-action"><Action disabled={!ready} onClick={()=>{discover(inspector);inspect(null);}}>{ready?'Archive discovery':inspector==='eagle'?`Inspect all parts / ${inspectedParts.length} of 3`:'Investigation incomplete'}</Action></div>
 </section>;}
function Journal({close}:{close:()=>void}){const{discovered}=useArchive(useShallow(s=>({discovered:s.discovered})));const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=dialog.current;el?.showModal();return()=>el?.close();},[]);return <dialog className="journal" ref={dialog} onCancel={e=>{e.preventDefault();close();}}><button className="quiet-button close-journal" onClick={close}>Close archive ×</button><p className="eyebrow">MERSA / EXPEDITION ARCHIVE</p><h2>Evidence of a species.</h2><p>{discovered.filter(id=>!isMarsArtifact(id)&&!isSpiritArtifact(id)&&!isOpportunityArtifact(id)).length} of 6 discoveries archived on the Moon. {discovered.filter(isMarsArtifact).length} of 4 at Ares Vallis. {discovered.filter(isSpiritArtifact).length} of 5 at Gusev Crater. {discovered.filter(isOpportunityArtifact).length} of 6 at Meridiani Planum.</p>{discovered.map(id=><article key={id}><h3>{artifacts[id].name}</h3><p>{artifacts[id].interpretation}</p><a href={artifacts[id].source} target="_blank" rel="noreferrer">Verified NASA source ↗</a></article>)}{!discovered.length&&<p>No records yet. Follow the signal to the surface.</p>}<details><summary>Imagery, reconstruction & credits</summary><p>A fictional alien expedition through real human history. The ship, landing handling, holographic separation and archive confidence are storytelling devices. The scene is not an exact archaeological survey.</p><ul><li><a href="https://svs.gsfc.nasa.gov/4720/" target="_blank" rel="noreferrer">Moon map: NASA SVS</a></li><li><a href="https://apod.nasa.gov/apod/ap180721.html" target="_blank" rel="noreferrer">Lunar panorama: Neil Armstrong / Apollo 11 / NASA</a></li><li><a href="https://science.nasa.gov/3d-resources/apollo-lunar-module/" target="_blank" rel="noreferrer">Lunar module model: NASA / Michael D. Carbajal</a></li><li><a href="https://svs.gsfc.nasa.gov/3895/" target="_blank" rel="noreferrer">Star map: NASA/Goddard SVS / Ernie Wright</a></li><li><a href="https://science.nasa.gov/resource/mars-planet-globe/" target="_blank" rel="noreferrer">Mars globe: NASA/JPL-Caltech, Viking mosaic</a></li></ul></details></dialog>;}
export default function App(){const{stage,setStage,inspector,inspect,discovered,muted,toggleMute,setPaused,paused}=useArchive(useShallow(s=>({stage:s.stage,setStage:s.setStage,inspector:s.inspector,inspect:s.inspect,discovered:s.discovered,muted:s.muted,toggleMute:s.toggleMute,setPaused:s.setPaused,paused:s.paused,identified:s.identified,historical:s.historical})));const[log,setLog]=useState(false);const[learning,setLearning]=useState(false);const[codePage,setCodePage]=useState(false);const guideOpener=useRef<HTMLElement|null>(null);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code==='Escape'&&inspector&&!(e.target as HTMLElement).closest('dialog'))inspect(null);if(e.code==='KeyE'&&stage==='entry')document.querySelector<HTMLButtonElement>('.scan-action')?.click();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[stage,inspector,inspect]);useEffect(()=>{if(stage==='approach')document.activeElement instanceof HTMLElement&&document.activeElement.blur();},[stage]);const done=discovered.filter(id=>!isMarsArtifact(id)&&!isSpiritArtifact(id)&&!isOpportunityArtifact(id)).length===6;useEffect(()=>{if(done&&stage==='explore'&&!inspector&&!paused&&!useArchive.getState().lunarSignalSeen){const t=setTimeout(()=>setStage('complete'),7000);return()=>clearTimeout(t);}},[done,stage,inspector,paused,setStage]);const openLog=()=>{clearControls();setPaused(true);setLog(true);};return <main className={`experience stage-${stage} ${inspector?'inspecting':''} ${['mars','spirit','mars-travel','opportunity','opportunity-travel'].includes(stage)?'chapter-mars':''}`}>
 {!['mars','spirit','travel','mars-travel','opportunity','opportunity-travel'].includes(stage)&&<MissionAudio/>}<WorldBoundary><Suspense fallback={<div className="world-loading">RESOLVING WORLD DATA…</div>}><World/></Suspense></WorldBoundary><div className={`sky-atmosphere ${paused?'paused':''}`} aria-hidden="true"><i className="sky-glow"/><i className="sky-streak"/></div>{(stage==='entry'||stage==='approach')&&<Cockpit/>}<div className="edge-shade"/><div className="grain" aria-hidden="true"/>
 <ArchiveIndex/><header className="hud"><button className="wordmark" onClick={openLog} aria-label="Open expedition archive">MERSA<span>INTERSTELLAR FIELD ARCHIVE</span></button><div className="chapter-track"><span className={['entry','signal','approach'].includes(stage)?'active':''}>01 / ARRIVAL</span><i/><span className={['surface','identified','explore'].includes(stage)?'active':''}>02 / EVIDENCE</span><i/><span className={stage==='complete'?'active':''}>03 / BEYOND</span></div><div className="header-actions">{(['explore','complete'].includes(stage)||stage==='mars'&&useArchive.getState().identified.includes('sojourner')||stage==='spirit'&&useArchive.getState().identified.includes('spirit')||stage==='opportunity'&&useArchive.getState().identified.includes('opportunity'))&&<button data-guide="true" onClick={e=>{guideOpener.current=e.currentTarget;clearControls();setPaused(true);setCodePage(false);setLearning(true);}}>FIELD GUIDE</button>}<button onClick={()=>{toggleMute();ping();}} aria-label={muted?'Enable audio':'Mute audio'}>{muted?'SOUND OFF':'SOUND ON'}</button><button onClick={openLog}>ARCHIVE <b>{String(discovered.length).padStart(2,'0')}</b></button></div></header>
 {!inspector&&<>
 {stage==='entry'&&<Arrival/>}
 {stage==='approach'&&<FlightHUD/>}
 {stage==='surface'&&<><WalkPrompt/><div className="landing-recording"><SoundClip kind="landing"/></div></>}
 {stage==='identified'&&<CatQuestion/>}
 {stage==='explore'&&<><div className="site-caption"><p className="eyebrow">TRANQUILITY BASE / SIX CLUES</p><h1>These objects tell a story.</h1><p>Choose a clue. Discover why it mattered.</p></div><button className="code-discovery" onClick={e=>{guideOpener.current=e.currentTarget;clearControls();setCodePage(true);setPaused(true);setLearning(true);}}><ClueIcon kind="code"/><span>BEHIND THE MISSION / 1969</span><strong>Discover the Apollo 11 code</strong><small>Open the computer that helped them land ↗</small></button><ExpeditionLog openLog={openLog} openJourney={()=>{guideOpener.current=document.activeElement as HTMLElement;clearControls();setCodePage(false);setPaused(true);setLearning(true);}}/><div className="surface-era"><span>{useArchive.getState().historical?'Full Eagle / historical reconstruction':'Descent stage / what stayed on the Moon'}</span><button onClick={()=>useArchive.getState().toggleHistorical()}>{useArchive.getState().historical?'See what remains today':'See the complete Eagle'}</button></div><nav className="discovery-dock" aria-label="Surface discoveries">{(['eagle','footprints','camera','seismometer','reflector','messages'] as ArtifactId[]).map((id,i)=><button key={id} data-artifact={id} onClick={()=>inspect(id)}><ClueIcon kind={id}/><span>{discovered.includes(id)?'✓':String(i+1).padStart(2,'0')}</span><strong>{discovered.includes(id)?id==='reflector'?<>Retro<wbr/>reflector</>:artifacts[id].name:artifacts[id].unknownName}</strong><small>{discovered.includes(id)?'ARCHIVED':'INVESTIGATE ↗'}</small></button>)}</nav>{done&&<div className="next-signal"><p className="eyebrow">ALIEN CONCLUSION</p><h2>These objects were not waste.<br/>They were evidence.</h2><Action onClick={()=>setStage('complete')}>Listen beyond the Moon</Action></div>}</>}
 {stage==='complete'&&<LunarSignal openLog={openLog}/>}
 {stage==='travel'&&<TravelHUD/>}{stage==='mars'&&<MarsSurface/>}{stage==='spirit'&&<SpiritSurface/>}{stage==='mars-travel'&&<SpiritTravelHUD/>}{stage==='opportunity'&&<OpportunitySurface/>}{stage==='opportunity-travel'&&<OpportunityTravelHUD/>}
 <footer className="world-footer"><span>{stage==='opportunity'?'MERIDIANI PLANUM / COMPOSITE RECONSTRUCTION':stage==='opportunity-travel'?'FICTIONAL MARS TRAVERSE':stage==='spirit'?'GUSEV CRATER / COMPOSITE RECONSTRUCTION':stage==='mars-travel'?'FICTIONAL MARS TRAVERSE':stage==='mars'?'ARES VALLIS / AUTHORED RECONSTRUCTION':stage==='travel'?'FICTIONAL ARCHIVE TRANSIT':stage==='complete'?'THE ARCHIVE CONTINUES':stage==='entry'||stage==='signal'?'NASA SVS LUNAR MAP / STAR CATALOG':'NASA APOLLO 11 IMAGERY / RECONSTRUCTED SCENE'}</span><div><span>HUMAN MODEL</span><b>{String(2+discovered.length*4).padStart(2,'0')}%</b></div></footer>
 </>}{inspector&&<Inspector key={inspector}/>}{learning&&<Learning codeOnly={codePage} close={()=>{setLearning(false);setPaused(false);requestAnimationFrame(()=>guideOpener.current?.focus());}}/>}{log&&<Journal close={()=>{setLog(false);setPaused(false);}}/>}
 </main>;}