import { useShallow } from 'zustand/react/shallow';
import { useEffect, useState } from 'react';
import { initialFlight, type FlightState } from './game/flight';
import { pressControl, clearControls } from './game/input';
import { useArchive } from './stores/archive';
function TouchControls(){const hold=(key:string,label:string)=><button key={key} aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);pressControl(key,true);}} onPointerUp={()=>pressControl(key,false)} onPointerCancel={()=>pressControl(key,false)} onLostPointerCapture={()=>pressControl(key,false)}>{label}</button>;return <div className="touch-controls"><div className="d-pad">{hold('KeyW','Forward')}{hold('KeyA','Left')}{hold('KeyS','Back')}{hold('KeyD','Right')}</div>{hold('Space','Brake')}</div>;}
export default function FlightHUD(){const[flight,setFlight]=useState<FlightState>(initialFlight());const{assist,toggleAssist,retryFlight,flightReset,paused,setPaused}=useArchive(useShallow(s=>({assist:s.assist,toggleAssist:s.toggleAssist,retryFlight:s.retryFlight,flightReset:s.flightReset,paused:s.paused,setPaused:s.setPaused})));
 useEffect(()=>{const update=(e:Event)=>setFlight((e as CustomEvent<FlightState>).detail);window.addEventListener('mersa-flight',update);return()=>window.removeEventListener('mersa-flight',update);},[]);useEffect(()=>setFlight(initialFlight()),[flightReset]);
 const offset=Math.hypot(flight.x,flight.z),drift=Math.hypot(flight.vx,flight.vz),descent=Math.abs(flight.vy);
 return <section className="flight-hud easy-flight" aria-label="Flight controls" data-altitude={flight.altitude.toFixed(1)} data-z={flight.z.toFixed(2)} data-offset={offset.toFixed(1)} data-drift={drift.toFixed(2)}>
 <div className="flight-objective"><p className="eyebrow">LUNAR APPROACH</p><h1>{assist?'You steer. I’ll help us land.':flight.altitude<12?'Hold Space for a soft landing.':'Fly toward the landing ring.'}</h1><p>{assist?'Release the keys to settle. Miso handles the descent.':'W / ↑ moves forward · Release to stop drifting · Hold Space to brake.'}</p></div>
 <div className="flight-displays">
  <section className="cockpit-screen telemetry-screen" aria-label="Flight measurements"><header><span>01 / FLIGHT</span><i>{paused?'PAUSED':assist?'STABILIZED':'MANUAL'}</i></header><div className="primary-measure"><span><strong>{Math.round(flight.altitude).toString().padStart(3,'0')}</strong><small>m · ALTITUDE</small></span><svg viewBox="0 0 55 90" aria-label="Altitude gauge" role="img"><path d="M15 5v80M15 5h25M15 25h15M15 45h25M15 65h15M15 85h25"/><path className="altitude-pointer" d={`M2 ${85-flight.altitude*.8}h11`}/></svg></div><dl><div><dt>DESCENT / M/S</dt><dd>{descent.toFixed(1)} <small>m/s</small></dd></div><div><dt>TARGET OFFSET / M</dt><dd>{offset.toFixed(1)}</dd></div><div><dt>THRUSTER RESERVE</dt><dd>{Math.round(flight.fuel)}<small>%</small></dd></div></dl></section>
  <section className="cockpit-screen map-screen" aria-label="Landing map"><header><span>02 / SURFACE MAP</span><i>LZ 01</i></header><svg viewBox="0 0 230 112" role="img" aria-label={`Craft is ${offset.toFixed(1)} metres from the landing zone`}><defs><pattern id="map-grid" width="23" height="22" patternUnits="userSpaceOnUse"><path d="M23 0H0V22" fill="none" stroke="#81cce322"/></pattern></defs><rect width="230" height="112" fill="url(#map-grid)"/><path className="map-contour" d="M0 25Q30 5 43 26T100 15T160 22T230 3M0 80Q35 65 72 92T135 80T230 91M10 0Q28 44 5 75M210 0Q185 50 224 112"/><circle className="map-zone" cx="115" cy="56" r="16"/><path className="map-guide" d={`M115 56L${115+Math.max(-98,Math.min(98,flight.x*2.5))} ${56+Math.max(-45,Math.min(45,flight.z*2.5))}`}/><path className="map-craft" transform={`translate(${115+Math.max(-98,Math.min(98,flight.x*2.5))},${56+Math.max(-45,Math.min(45,flight.z*2.5))})`} d="M0-6L5 5 0 2-5 5Z"/><text x="137" y="54">LAND HERE</text></svg><footer><span>OFFSET <b>{offset.toFixed(1)} m</b></span><span>{offset<4.2?'ON TARGET':'FOLLOW THE LINE'}</span></footer></section>
 </div>
 <div className="flight-help"><p><kbd>W A S D</kbd> / arrows · steer <kbd>SPACE</kbd> · slow down</p><div><button className="quiet-button" aria-pressed={assist} onClick={e=>{clearControls();toggleAssist();e.currentTarget.blur();}}>{assist?'Flight assist on':'Enable flight assist'}</button><button className="quiet-button" onClick={()=>{clearControls();setPaused(!paused);}}>{paused?'Resume flight':'Pause flight'}</button></div></div><TouchControls/>
 {paused&&<div className="flight-message" role="status"><p className="eyebrow">FLIGHT PAUSED</p><h2>Take your time.</h2><button className="action" onClick={()=>setPaused(false)}>Resume flight</button></div>}
 {flight.failed&&<div className="flight-message" role="alert"><p className="eyebrow">CRAFT RECOVERED</p><h2>{offset>6?'Outside the landing zone.':'Approach speed too high.'}</h2><p>Steer into the ring, then hold Space. Flight assist is available below.</p><button className="action" onClick={()=>{clearControls();retryFlight();useArchive.setState({assist:false,paused:false});}}>Retry landing</button></div>}
 {flight.landed&&<div className="landing-success" role="status">TOUCHDOWN / WELCOME TO THE MOON</div>}
 </section>;
}
