import { useShallow } from 'zustand/react/shallow';
import { useEffect, useState } from 'react';
import { useArchive } from './stores/archive';
import { clearControls, pressControl } from './game/input';

export function Cockpit(){return <div className="cockpit open-canopy" aria-hidden="true"><div className="canopy-reticle"><span>+</span></div></div>;}
export function Arrival(){const {setStage,paused}=useArchive(useShallow(s=>({setStage:s.setStage,paused:s.paused})));const launch=()=>{clearControls();useArchive.setState({assist:false});setStage('approach');};useEffect(()=>{if(paused||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=setTimeout(launch,4200);return()=>clearTimeout(timer);},[paused]);return <section className="arrival"><p className="eyebrow">Sol-3 / FIRST CONTACT</p><h1>Something is down there.</h1><button className="action" onClick={launch}>Land on the Moon <span aria-hidden="true">↓</span></button><small>WASD to steer · Space to brake</small></section>;}
export function WalkPrompt(){const {walk,setWalk,setStage}=useArchive(useShallow(s=>({walk:s.walk,setWalk:s.setWalk,setStage:s.setStage})));const hold=(down:boolean)=>pressControl('KeyW',down);return <section className="walk-prompt"><p className="eyebrow">TOUCHDOWN</p><h1>{walk<1?'Follow the footprints.':'What did they leave behind?'}</h1>{walk<1?<><p>Hold <kbd>W</kbd> or ↑ to walk.</p><button className="action" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);hold(true);}} onPointerUp={()=>hold(false)} onPointerCancel={()=>hold(false)} onLostPointerCapture={()=>hold(false)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')hold(true);}} onKeyUp={()=>hold(false)}>Hold to walk →</button><button className="quiet-button" onClick={()=>{clearControls();setWalk(1);}}>Skip walk</button></>:<button className="action" onClick={()=>{clearControls();setStage('identified');}}>Scan the unknown hardware <span aria-hidden="true">+</span></button>}</section>;}
const questions=[
 {question:'When did Eagle land on the Moon?',options:['20 July 1969','12 April 1961','6 August 2012'],answer:0,note:'Eagle landed on 20 July 1969.'},
 {question:'How many Apollo 11 astronauts walked here?',options:['One','Two','Three'],answer:1,note:'Neil Armstrong and Buzz Aldrin walked on the Moon.'},
 {question:'What was their lunar module called?',options:['Columbia','Voyager','Eagle'],answer:2,note:'Eagle carried Armstrong and Aldrin to the surface.'}
];
export function CatQuestion(){const[q]=useState(()=>questions[Math.floor(Math.random()*questions.length)]);const[answer,setAnswer]=useState<number|null>(null);const setStage=useArchive(s=>s.setStage);return <section className="cat-question" aria-label="Alien cat question"><img src="/textures/alien-cat.png" alt="A curious alien cat in a space helmet"/><div><p className="eyebrow">MISO / YOUR CURIOUS COPILOT</p><h1>APOLLO 11</h1><p>{q.question}</p><div className="quiz-options">{q.options.map((option,i)=><button key={option} aria-pressed={answer===i} className={answer===null?'':i===q.answer?'answer-correct':answer===i?'answer-wrong':''} onClick={()=>setAnswer(i)}><span>{option}</span>{answer!==null&&i===q.answer&&<small>Correct answer</small>}{answer===i&&i!==q.answer&&<small>Incorrect</small>}</button>)}</div>{answer!==null&&<p role="status">{answer===q.answer?'You got it!':'Oops, not quite.'} {q.note} <a href="https://www.nasa.gov/history/apollo-11-mission-overview/" target="_blank" rel="noreferrer">NASA ↗</a></p>}<button className="action" onClick={()=>setStage('explore')}>{answer===null?'Explore without answering':'Let’s explore'} <span aria-hidden="true">→</span></button></div></section>;}
