import { useShallow } from 'zustand/react/shallow';
import { afterPaint } from './afterPaint';
import { AirbagEvidence, PathfinderEvidence, PathfinderResources } from './MarsEvidence';
import { useEffect, useRef, useState } from 'react';
import { useArchive, builtChapters, type Chapter } from './stores/archive';
import { marsArtifacts, marsIds, marsParts, marsSources, type MarsArtifactId } from './data/mars';
import PartPoster from './PartPoster';
import { clearControls } from './game/input';

export function ArchiveIndex(){const {chapter,visitChapter,stage}=useArchive(useShallow(s=>({chapter:s.chapter,visitChapter:s.visitChapter,stage:s.stage})));const [open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const trigger=useRef<HTMLButtonElement>(null);const priorPause=useRef(false);const pending=useRef<(()=>void)|null>(null);
 useEffect(()=>()=>pending.current?.(),[]);
 useEffect(()=>{if(open){const wasPending=!!pending.current;pending.current?.();pending.current=null;void import('./three/preloadChapters').then(({preloadChapter})=>{preloadChapter('apollo11');preloadChapter('spirit');preloadChapter('opportunity');preloadChapter('voyager');});if(!wasPending)priorPause.current=useArchive.getState().paused;clearControls();useArchive.getState().setPaused(true);dialog.current?.showModal();}else dialog.current?.close();},[open]);
 const close=(destination?:Chapter)=>{
  pending.current?.();dialog.current?.close();setOpen(false);trigger.current?.focus();
  if(destination)pending.current=afterPaint(()=>{visitChapter(destination);pending.current=null;});
  else useArchive.getState().setPaused(priorPause.current);
 };
 const current=stage==='entry'?'prologue':stage==='mars'?'sojourner':chapter;
 return <><button ref={trigger} className="archive-index-trigger" aria-haspopup="dialog" aria-expanded={open} aria-controls="archive-index" onClick={()=>setOpen(true)}>ARCHIVE / {current==='prologue'?'PR':current==='sojourner'?'CH-02':current==='spirit'?'CH-03':current==='opportunity'?'CH-04':current==='voyager'?'CH-05':'CH-01'} ▾</button>
 <dialog ref={dialog} id="archive-index" className="archive-index" aria-labelledby="archive-index-title" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}}>
 <header><h2 id="archive-index-title">Archive Index</h2><button onClick={()=>close()} aria-label="Close Archive Index">×</button></header><p className="eyebrow">MERSA / RECOVERED COORDINATES</p>
 {builtChapters.map((id,i)=><button key={id} aria-current={current===id?'location':undefined} onClick={()=>close(id)}><span>{['PROLOGUE','01 — APOLLO 11','02 — SOJOURNER','03 — SPIRIT','04 — OPPORTUNITY','05 / VOYAGER 1'][i]}</span><small>{current===id?'ACTIVE':'OPEN'}</small></button>)}
 <p className="archive-index-note">Recovered records remain in this expedition.</p>
 </dialog></>;
}
export function LunarSignal({openLog}:{openLog:()=>void}){const {startTravel,setStage,restart}=useArchive(useShallow(s=>({startTravel:s.startTravel,setStage:s.setStage,restart:s.restart})));return <section className="lunar-signal" aria-label="Mars signal"><p className="eyebrow">UNIDENTIFIED SIGNAL DETECTED</p><h1>MARS</h1><p>ORIGIN: MARS</p><div className="signal-rule"/><p className="eyebrow" role="status">MARS ARCHIVE AVAILABLE</p><button className="action" onClick={startTravel}>Continue to Mars <span aria-hidden="true">↗</span></button><button className="quiet-button" onClick={openLog}>Read the expedition archive</button><button className="quiet-button" onClick={()=>setStage('explore')}>Return to the Moon</button><button className="quiet-button" onClick={restart}>Restart expedition</button></section>;}
export function TravelHUD(){const {travelProgress:p,paused,setPaused,setStage}=useArchive(useShallow(s=>({travelProgress:s.travelProgress,paused:s.paused,setPaused:s.setPaused,setStage:s.setStage})));const veil=Math.max(0,1-Math.abs(p-.36)/.065,1-Math.abs(p-.68)/.065);return <><div className="travel-veil" style={{opacity:veil}}/><section className="travel-hud" aria-label="Travel to Mars"><p className="eyebrow">ARCHIVE TRANSIT / 01 → 02</p><p role="status">{p<.3?'Human trace detected.':p<.68?'Distance from origin increasing.':'Investigate.'}</p><div className="travel-line"><i style={{width:`${p*100}%`}}/></div><button className="quiet-button" onClick={()=>setPaused(!paused)}>{paused?'Resume journey':'Pause journey'}</button><button className="quiet-button" onClick={()=>{setPaused(false);setStage('mars');}}>Skip travel</button></section></>;}
export function MarsSurface(){const {marsApproached,approachMars,inspect,identified,discovered,startSpiritTravel}=useArchive(useShallow(s=>({marsApproached:s.marsApproached,approachMars:s.approachMars,inspect:s.inspect,identified:s.identified,discovered:s.discovered,startSpiritTravel:s.startSpiritTravel})));const records=marsIds.filter(id=>discovered.includes(id));const available=marsIds.filter(id=>id!=='tracks'||['sojourner','pathfinder','airbags'].every(x=>discovered.includes(x as MarsArtifactId)));return <>
 <div className="site-caption mars-caption"><p className="eyebrow">CH-02 / ARES VALLIS</p><h1>{records.length===4?'Small was not insignificant.':identified.includes('sojourner')?'A small explorer. An enormous world.':'Something small. Very far from home.'}</h1><p>{records.length===4?'MARS ARCHIVE COMPLETE / 04 RECORDS':marsApproached?'Follow the evidence. Learn what it could do.':'Human trace detected in the dust.'}</p></div>
 {!marsApproached&&<div className="mars-approach"><p>Why send something this small this far?</p><button className="action" onClick={approachMars}>Approach the signal <span aria-hidden="true">↗</span></button></div>}
 {marsApproached&&<nav className="discovery-dock mars-dock" aria-label="Mars discoveries">{available.map((id,i)=><button key={id} data-artifact={id} onClick={()=>inspect(id)}><span>{discovered.includes(id)?'✓':`0${i+1}`}</span><strong>{identified.includes(id)?marsArtifacts[id].name:marsArtifacts[id].unknownName}</strong><small>{discovered.includes(id)?'ARCHIVED':identified.includes(id)?'INSPECT ↗':'DETECT / SCAN ↗'}</small></button>)}</nav>}
 <div className="mars-site-note">{records.length} / 04 RECORDS<br/>RECONSTRUCTED LANDING SITE</div>{records.length===4&&<aside className="spirit-next-signal"><p className="eyebrow">ANOTHER TRACE / GUSEV CRATER</p><h2>The questions grew.</h2><button className="action" onClick={startSpiritTravel}>Continue to Gusev Crater</button></aside>}
 </>;}
export function MarsInspector({id}:{id:MarsArtifactId}){const {inspect,identified,identify,scanProgress,setScanProgress,selected,select,inspectedParts,exploded,toggleExploded,resetView,discover,evidenceStep}=useArchive(useShallow(s=>({inspect:s.inspect,identified:s.identified,identify:s.identify,scanProgress:s.scanProgress,setScanProgress:s.setScanProgress,selected:s.selected,select:s.select,inspectedParts:s.inspectedParts,exploded:s.exploded,toggleExploded:s.toggleExploded,resetView:s.resetView,discover:s.discover,evidenceStep:s.evidenceStep})));const known=identified.includes(id);const [scanning,setScanning]=useState(false);const [revealed,setRevealed]=useState(false);const close=useRef<HTMLButtonElement>(null);const a=marsArtifacts[id];const ready=known&&(id==='sojourner'?inspectedParts.length>=3:id==='pathfinder'?evidenceStep>=2:id==='airbags'?evidenceStep>=4:revealed);
 useEffect(()=>{close.current?.focus();},[]);
 useEffect(()=>{if(!scanning)return;let frame=0,last=performance.now(),p=0;const tick=(now:number)=>{if(!useArchive.getState().paused)p+=Math.min(now-last,100)/1800;last=now;if(matchMedia('(prefers-reduced-motion: reduce)').matches)p=1;setScanProgress(Math.min(1,p));if(p>=1){identify(id);setScanning(false);}else frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[scanning,id,identify,setScanProgress]);
 return <section className={`investigation mars-investigation ${known?'resolved':''}`} role="region" aria-label="Artifact inspection"><div className="investigation-title"><p className="eyebrow">{a.code} / {known?'SPATIAL ANALYSIS':'UNIDENTIFIED HARDWARE'}</p><h2>{known?a.name:a.unknownName}</h2></div><button ref={close} className="exit-inspection" onClick={()=>inspect(null)}>ESC / Return to surface <span>×</span></button>
 {!known?<div className="mars-scan-panel"><p className="eyebrow">{scanning?'SCANNING / MATCHING ARCHIVE':'APPROACH COMPLETE / TRACE RESOLVED'}</p><div className="travel-line"><i style={{width:`${scanProgress*100}%`}}/></div><button className="action" disabled={scanning} onClick={()=>setScanning(true)}>{scanning?'Scanning…':'Scan object'}</button><small>Reconstruction / position and condition are interpretive.</small></div>:<>
 {id==='sojourner'?<><nav className="component-switch" aria-label="Hardware components">{marsParts.map((p,i)=><button key={p.id} aria-pressed={selected===p.id} onClick={()=>select(p.id)}><span>0{i+1}</span>{p.name}<small>{selected===p.id?'✓':'+'}</small></button>)}</nav>{selected&&<PartPoster part={`mars-${selected}`} conclusion={ready?a.interpretation:undefined}/>}<div className="mars-model-tools"><button className="quiet-button" onClick={toggleExploded}>{exploded?'Assemble':'Separate'} hardware</button><button className="quiet-button" onClick={resetView}>Reset view</button>{['left','right','in','out'].map((v,i)=><button key={v} className="quiet-button" aria-label={['Rotate model left','Rotate model right','Zoom in','Zoom out'][i]} onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:v}))}>{['↶','↷','+','−'][i]}</button>)}</div><p className="mars-orbit-hint">Drag to orbit / Scroll to zoom / Select a part</p></>:<aside className="part-poster floating-lesson mars-note" tabIndex={0} aria-label={`${a.name} field note`}><header className="poster-presenter"><img src="/textures/alien-cat.png" alt="Miso the alien cat"/><div><span>MISO’S DISCOVERY</span><p>{id==='pathfinder'?'How did it speak to home?':id==='airbags'?'How did it survive the landing?':'How long could such a small explorer keep going?'}</p></div></header><h3>{id==='tracks'&&!revealed?'Mission duration / unread':a.subtitle}</h3><>{id==='pathfinder'?<PathfinderEvidence/>:id==='airbags'?<AirbagEvidence/>:<button className="action" onClick={()=>setRevealed(true)}>Recover the mission log</button>}</>{ready&&<><div className="mars-demonstration" role="status">{id==='pathfinder'?'ROVER → STATION → EARTH':id==='airbags'?'INFLATE → BOUNCE → DEFLATE → OPEN':'7 SOLS PLANNED → 83 SOLS EXPLORING'}</div><p className="lesson-prose">{a.purpose}</p><p className="evidence-conclusion poster-conclusion"><small>FICTIONAL ALIEN INTERPRETATION</small>{a.interpretation}</p><a className="poster-source" href={a.source} target="_blank" rel="noreferrer">NASA source ↗</a>{id==='tracks'&&<a className="poster-source" href={marsSources.lifetime} target="_blank" rel="noreferrer">NASA / planned mission lifetime ↗</a>}<p className="mars-reconstruction">Schematic reconstruction. Tracks, remnant positions and preservation are illustrative, not an exact archaeological survey.</p></>}</aside>}
 <div className="archive-action"><button className="action" disabled={!ready} onClick={()=>{discover(id);inspect(null);}}>{ready?'Archive discovery':id==='sojourner'?`Inspect all parts / ${inspectedParts.length} of 3`:'Investigation incomplete'}</button></div></>}
 </section>;
}
export function MarsGuideBody(){const {identified,discovered}=useArchive(useShallow(s=>({identified:s.identified,discovered:s.discovered})));return <div className="learning-body"><p className="eyebrow">NASA EVIDENCE / MARS, 1997</p><h2 id="learning-title">Sojourner: a small beginning.</h2><p className="learning-intro">Your field guide grows as you identify the evidence.</p><div className="learning-story"><figure><img style={{width:'100%'}} src="/learning/sojourner-sol2.jpg" alt="NASA mosaic of Sojourner on Mars on Sol 2"/><figcaption>NASA / JPL · Sol 2 mosaic · <a href="https://www.nasa.gov/image-article/nasas-first-rover-red-planet/" target="_blank" rel="noreferrer">Original evidence ↗</a></figcaption></figure><article><h3>Ares Vallis</h3><p>Pathfinder landed on July 4, 1997. This rocky plain offered a chance to investigate material that ancient floods may have gathered together.</p><a href={marsSources.mission} target="_blank" rel="noreferrer">NASA / Mars Pathfinder ↗</a>{marsIds.filter(id=>identified.includes(id)).map(id=><section key={id}><h3>{marsArtifacts[id].name}</h3><p>{id==='tracks'&&!discovered.includes('tracks')?'Recover the mission log to reveal its duration.':marsArtifacts[id].purpose}</p><a href={marsArtifacts[id].source} target="_blank" rel="noreferrer">NASA evidence ↗</a></section>)}</article></div><PathfinderResources/><h3>Reading this archive</h3><p>The alien expedition and Miso’s interpretations are fiction. Hardware is an authored reconstruction based on mission references. Terrain, tracks, dust, travel, and distant entry remnants are illustrative. They do not establish exact locations, current condition, or a future archaeological survey.</p></div>;}
