const milestones = [
  ['16 JUL', 'Leave Earth', 'A Saturn V rocket lifted Armstrong, Aldrin and Collins from Launch Pad 39A in Florida.', 'After a short stay in Earth orbit, another rocket burn sent them toward the Moon. Columbia then docked with Eagle so the two spacecraft could travel together.'],
  ['19 JUL', 'Go into lunar orbit', 'An engine burn slowed the spacecraft so the Moon could hold it in orbit.', 'The burn happened behind the Moon, where Earth could not receive their radio signals. The crew later checked the lander before separating.'],
  ['20 JUL', 'Land Eagle', 'Armstrong and Aldrin landed in the Sea of Tranquility. Collins stayed in orbit aboard Columbia.', 'Armstrong steered past a crater during the final approach. Eagle’s landing engine controlled the descent; its lower stage would stay on the Moon.'],
  ['21 JUL · UTC', 'Explore on foot', 'Armstrong stepped out first. Aldrin followed. They gathered samples, took pictures and set out experiments.', 'The first step happened on July 21 in UTC, but it was still July 20 in the United States. The surface excursion lasted more than two and a half hours.'],
  ['21 JUL', 'Meet Columbia again', 'Eagle’s upper stage lifted off. The two moonwalkers rejoined Collins with their samples.', 'They spent about 21 hours and 36 minutes on the lunar surface before liftoff. The landing legs, lower stage and surface experiments stayed behind.'],
  ['24 JUL', 'Come home', 'Columbia splashed down in the Pacific Ocean. USS Hornet recovered the crew.', 'A heat shield protected the capsule during re-entry. Parachutes slowed its final fall. The mission lasted eight days, three hours and about nineteen minutes.'],
];

export default function MissionOverview() {
  return <>
    <section className="mission-overview" id="learn-mission" aria-labelledby="mission-heading">
      <div><p className="eyebrow">01 / THE MISSION</p><h3 id="mission-heading">Land. Learn. Return safely.</h3><p>Apollo 11’s main goal was to land people on the Moon and bring them home. It fulfilled the goal President Kennedy set in 1961.</p><p>The crew also collected lunar material, photographed the landscape and left tools to study the Moon. Their television camera let people on Earth share the moment.</p><a href="https://www.nasa.gov/mission/apollo-11/" target="_blank" rel="noreferrer">NASA mission overview and flight history ↗</a></div>
      <dl className="mission-facts"><div><dt>Neil Armstrong</dt><dd>Commander · first person to step onto the Moon</dd></div><div><dt>Buzz Aldrin</dt><dd>Lunar module pilot · explored the surface with Armstrong</dd></div><div><dt>Michael Collins</dt><dd>Command module pilot · flew Columbia in lunar orbit</dd></div><div><dt>Two spacecraft, different jobs</dt><dd>Eagle: land and lift off. Columbia: carry the crew home.</dd></div></dl>
    </section>
    <section className="mission-timeline" id="learn-timeline" aria-labelledby="timeline-heading"><p className="eyebrow">02 / EIGHT DAYS THAT CHANGED EXPLORATION</p><h3 id="timeline-heading">Follow the journey.</h3><p>Open a moment to find out what happened next. Dates are in 1969; the first-step date below uses UTC.</p><ol>{milestones.map(([date,title,summary,detail])=><li key={title}><time>{date}</time><details><summary>{title}</summary><p>{summary}</p><p className="timeline-detail">{detail}</p></details></li>)}</ol></section>
    <section className="mission-science" aria-labelledby="science-heading"><p className="eyebrow">03 / MORE THAN A FOOTPRINT</p><h3 id="science-heading">What did they leave for science?</h3><div><article><h4>Listen to the Moon</h4><p>A seismometer measured shaking. It helped scientists investigate what happens inside the Moon.</p></article><article><h4>Measure the distance</h4><p>A reflector sent laser light back toward Earth. Timing the round trip helped measure the Earth–Moon distance.</p></article><article><h4>Catch particles from the Sun</h4><p>A sheet of foil collected solar-wind particles. The crew brought it home for scientists to study.</p></article></div><p>They also brought samples home and left messages of goodwill. The silicon disc carried messages from 73 countries.</p><a href="https://www.nasa.gov/mission/apollo-11/" target="_blank" rel="noreferrer">Read NASA’s mission objectives and results ↗</a></section>
  </>;
}
