import { useShallow } from 'zustand/react/shallow';
import { useEffect, useRef, useState } from 'react';
import { useArchive } from './stores/archive';
import { opportunityArtifacts, opportunityIds, opportunityParts, opportunitySources, type OpportunityArtifactId } from './data/opportunity';
import PartPoster from './PartPoster';
import { PhotoReveal } from './Learning';

export function OpportunityTravelHUD(){
  const {travelProgress,paused,setPaused,setStage}=useArchive(useShallow(s=>({travelProgress:s.travelProgress,paused:s.paused,setPaused:s.setPaused,setStage:s.setStage})));
  return <><div className="travel-veil" style={{opacity:Math.max(0,1-Math.abs(travelProgress-.5)/.13)}}/><section className="travel-hud" aria-label="Travel to Meridiani Planum"><p className="eyebrow">ARCHIVE TRANSIT / 03 → 04</p><h2>{travelProgress<.5?'The archive remembers a twin.':'Ninety sols was only the beginning.'}</h2><p className="eyebrow">GUSEV CRATER → MERIDIANI PLANUM / COMPRESSED FICTIONAL TRAVEL</p><div className="travel-line"><i style={{width:`${travelProgress*100}%`}}/></div><button className="quiet-button" onClick={()=>setPaused(!paused)}>{paused?'Resume journey':'Pause journey'}</button><button className="quiet-button" onClick={()=>{setPaused(false);setStage('opportunity');}}>Skip travel</button></section></>;
}

export function OpportunitySurface(){
  const {opportunityApproached,approachOpportunity,identified,discovered,inspect}=useArchive(useShallow(s=>({opportunityApproached:s.opportunityApproached,approachOpportunity:s.approachOpportunity,identified:s.identified,discovered:s.discovered,inspect:s.inspect})));
  const count=opportunityIds.filter(id=>discovered.includes(id)).length;
  const available=opportunityIds.filter(id=>id!=='opportunityLog'||count>=5||discovered.includes(id));
  return <>
    <div className="site-caption mars-caption"><p className="eyebrow">CH-04 / MERIDIANI PLANUM</p><h1>{count===6?'The journey outlasted the plan.':identified.includes('opportunity')?'How far can curiosity carry you?':'A familiar shape. A longer story.'}</h1><p>{count===6?'SIX RECORDS RECOVERED':opportunityApproached?'A machine, a mistaken snack, and a very patient escape.':'Miso recognizes the silhouette. The story is different.'}</p></div>
    {!opportunityApproached?<div className="mars-approach"><p>“Did Spirit take a shortcut?” Miso wonders.</p><button className="action" onClick={approachOpportunity}>Approach the familiar trace ↗</button></div>:<nav className="discovery-dock mars-dock spirit-dock opportunity-dock" aria-label="Opportunity discoveries">{available.map((id,i)=><button key={id} data-artifact={id} onClick={()=>inspect(id)}><span>{discovered.includes(id)?'✓':`0${i+1}`}</span><strong>{identified.includes(id)?opportunityArtifacts[id].name:opportunityArtifacts[id].unknownName}</strong><small>{discovered.includes(id)?'ARCHIVED':identified.includes(id)?'INSPECT ↗':'DETECT / SCAN ↗'}</small></button>)}</nav>}
    <div className="mars-site-note">{count} / 06 RECORDS<br/>COMPOSITE SCIENCE LANDSCAPE<br/>SITES AND DISTANCES ARE SCHEMATIC</div>
    {count===6&&<aside className="spirit-next-signal"><p className="eyebrow">SIX RECORDS / ONE LONG JOURNEY</p><h2>There was always another question.</h2><p>Miso saves the route, the mistakes, and the discoveries. Beyond Mars, a faint signal waits.</p><button className="action" onClick={()=>useArchive.getState().startVoyagerTravel()}>Follow the deep-space signal</button></aside>}
  </>;
}

export const opportunityInvestigations = {
  opportunityLanding: {photo:'opportunityLanding',prompt:'“A nest?” Miso asks. What had to open before a rover could leave?',actions:['Unfold the landing cradle','Trace the discarded descent system','Follow the rover off the lander'],steps:['Airbags cushioned touchdown inside Eagle Crater. Opening lander petals made a platform for departure. The moving geometry is a schematic, not landing footage.','The backshell and parachute were discarded during descent. They are separate from the lander; this exhibit compresses their real distances.','Opportunity left Challenger Memorial Station and began exploring. The station stayed behind while the rover’s route grew.'],diagram:['CUSHION','OPEN','DRIVE AWAY']},
  heatShieldRock: {photo:'opportunityHeatshield',prompt:'“That rock came off the robot!” Miso decides. Does the evidence agree?',actions:['Compare the two surfaces','Read the composition finding','Separate the two histories'],steps:['One object has torn sheet material and manufactured layers. The other is a pitted, rounded rock. Appearance starts the question; it does not settle it.','Archived measurements identified iron and nickel in Heat Shield Rock. The rover team recognized a meteorite, not another piece of the shield.','The heat shield protected arrival through the atmosphere. The meteorite arrived naturally from space. Nearby does not mean related.'],diagram:['OBSERVE','MEASURE','DISTINGUISH']},
  blueberries: {photo:'opportunityBerries',prompt:'“Mars has snacks!” Miso announces. Let’s check before anyone takes a bite.',actions:['Look closely at the spheres','Compare the mineral evidence','Reconstruct the water clue'],steps:['Small, rounded spheres sit within the outcrop and on its surface. They look more gray than blue; “blueberries” is a nickname.','Scientists compared sphere-rich material with other parts of the outcrop. The spheres were rich in the mineral hematite.','Alongside the surrounding rock evidence, these mineral concretions supported a history involving liquid water. They are neither fruit nor proof of life.'],diagram:['TEXTURE','HEMATITE','PAST WATER']},
  purgatory: {photo:'opportunityDune',prompt:'“Floor it?” says Miso. First, try both ideas in the little Earth sandbox.',actions:['Test more wheel spin','Test a careful retreat','Read the real recovery'],steps:['The schematic wheel spins while the body stays put: loose material slips beneath it. More spinning is not automatically more progress.','In this simplified demonstration, small controlled movements retreat from the ripple. Engineers on Earth tested strategies before sending careful commands.','Opportunity escaped after more than five weeks. This animation explains the idea; it does not reproduce the actual command sequence or exact wheel motions.'],diagram:['NOTICE SLIP','TEST ON EARTH','MOVE CAREFULLY']},
  opportunityLog: {photo:'opportunityRoute',prompt:'“Ninety days?” Miso checks the calendar. “We may need a bigger calendar.”',actions:['Unroll the route','Read the final sky observation','Save the completed mission'],steps:['The plan called for 90 Martian days, or sols. Opportunity operated for 5,111 sols and traveled 45.16 kilometers, from Eagle Crater toward Endeavour Crater.','A planet-wide storm darkened the sky in 2018. Opportunity’s last signal was received on June 10. The famous poetic “last words” were a human paraphrase, not a sentence transmitted by the rover.','NASA declared the mission complete on February 13, 2019. Miso cannot restart the historical rover. The archive can preserve what it taught us.'],diagram:['90 → 5,111 SOLS','2018 / LAST CONTACT','2019 / MISSION COMPLETE']},
} as const;

export function OpportunityInspector({id}:{id:OpportunityArtifactId}){
  const {identified,identify,scanProgress,setScanProgress,inspect,selected,select,inspectedParts,exploded,toggleExploded,isolated,toggleIsolated,resetView,discover,evidenceStep,setEvidenceStep}=useArchive(useShallow(s=>({identified:s.identified,identify:s.identify,scanProgress:s.scanProgress,setScanProgress:s.setScanProgress,inspect:s.inspect,selected:s.selected,select:s.select,inspectedParts:s.inspectedParts,exploded:s.exploded,toggleExploded:s.toggleExploded,isolated:s.isolated,toggleIsolated:s.toggleIsolated,resetView:s.resetView,discover:s.discover,evidenceStep:s.evidenceStep,setEvidenceStep:s.setEvidenceStep})));
  const close=useRef<HTMLButtonElement>(null);const note=useRef<HTMLElement>(null);const [scanning,setScanning]=useState(false);
  const a=opportunityArtifacts[id],known=identified.includes(id),story=id==='opportunity'?null:opportunityInvestigations[id];
  const ready=known&&(id==='opportunity'?opportunityParts.every(p=>inspectedParts.includes(p.id)):evidenceStep>=(story?.actions.length??1));
  useEffect(()=>{close.current?.focus();},[]);
  useEffect(()=>{if(!scanning)return;let frame=0,p=0,last=performance.now();const tick=(now:number)=>{if(!useArchive.getState().paused)p+=Math.min(now-last,100)/1400;last=now;if(matchMedia('(prefers-reduced-motion: reduce)').matches)p=1;setScanProgress(Math.min(1,p));if(p>=1){identify(id);setScanning(false);}else frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[scanning,id,identify,setScanProgress]);
  return <section className="investigation mars-investigation spirit-investigation opportunity-investigation" role="region" aria-label="Artifact inspection">
    <div className="investigation-title"><p className="eyebrow">{a.code} / {known?'SPATIAL ANALYSIS':'UNIDENTIFIED TRACE'}</p><h2>{known?a.name:a.unknownName}</h2></div>
    <button ref={close} className="exit-inspection" onClick={()=>inspect(null)}>ESC / Return to surface <span>×</span></button>
    {!known?<div className="mars-scan-panel"><p className="eyebrow">{scanning?'MATCHING THE ARCHIVE':'TRACE ACQUIRED'}</p><div className="travel-line"><i style={{width:`${scanProgress*100}%`}}/></div><button className="action" disabled={scanning} onClick={()=>setScanning(true)}>{scanning?'Scanning…':'Scan object'}</button><small>Historical evidence within a fictional expedition.</small></div>:<>
      {id==='opportunity'?<>
        <nav className="component-switch" aria-label="Hardware components">{opportunityParts.map((p,i)=><button key={p.id} aria-pressed={selected===p.id} onClick={()=>select(p.id)}><span>0{i+1}</span>{p.name}<small>{selected===p.id?'✓':'+'}</small></button>)}</nav>
        {selected&&<PartPoster part={`opportunity-${selected}`} conclusion={ready?a.interpretation:undefined}/>}
        <div className="mars-model-tools"><button className="quiet-button" aria-pressed={exploded} onClick={toggleExploded}>{exploded?'Assemble':'Separate'} hardware</button><button className="quiet-button" disabled={!selected} aria-pressed={isolated} onClick={toggleIsolated}>{isolated?'Show all parts':'Isolate selection'}</button><button className="quiet-button" onClick={resetView}>Reset view</button>{['left','right','in','out'].map((v,i)=><button key={v} className="quiet-button" aria-label={['Rotate model left','Rotate model right','Zoom in','Zoom out'][i]} onClick={()=>window.dispatchEvent(new CustomEvent('model-control',{detail:v}))}>{['↶','↷','+','−'][i]}</button>)}</div>
        <p className="mars-orbit-hint">Drag to orbit / Scroll to zoom / Reference-based rover reconstruction</p>
      </>:story&&<aside ref={note} className="part-poster floating-lesson mars-note" tabIndex={0} aria-label={`${a.name} field note`}>
        <header className="poster-presenter"><img src="/textures/alien-cat.png" alt="Miso the alien cat"/><div><span>MISO’S DISCOVERY</span><p>{story.prompt}</p></div></header>
        <h3>{id==='opportunityLog'&&!ready?'A mission record, unread':a.subtitle}</h3><PhotoReveal photo={id==='opportunityLog'&&evidenceStep===2?'opportunityFinal':id==='heatShieldRock'&&evidenceStep>=2?'opportunityMeteorite':story.photo}/>
        <ol className="evidence-workflow" aria-label="Investigation steps">{story.diagram.map((label,i)=><li key={label} className={evidenceStep>i?'observed':''}>{label}</li>)}</ol>
        <p className="mars-reconstruction">{id==='blueberries'&&evidenceStep>0?'Enlarged schematic mineral sample / not actual scale.':id==='purgatory'?'Schematic traction demonstration / not a historical replay.':'Interactive reconstruction / no live science data.'}</p>
        {evidenceStep<story.actions.length&&<button className="action" onClick={()=>{setEvidenceStep(evidenceStep+1);requestAnimationFrame(()=>note.current?.querySelector<HTMLElement>('[role="status"]')?.scrollIntoView({block:'nearest'}));}}>{story.actions[evidenceStep]}</button>}
        {evidenceStep>0&&<p className="lesson-prose" role="status">{story.steps[evidenceStep-1]}</p>}
        {ready&&<><p className="lesson-prose">{a.purpose}</p><p className="evidence-conclusion poster-conclusion"><small>FICTIONAL ALIEN INTERPRETATION</small>{a.interpretation}</p><button className="quiet-button replay-evidence" onClick={()=>setEvidenceStep(0)}>Replay investigation</button></>}
        <a className="poster-source" href={a.source} target="_blank" rel="noreferrer">Read the NASA source ↗</a>
      </aside>}
      <div className="archive-action"><button className="action" disabled={!ready} onClick={()=>{discover(id);inspect(null);}}>{ready?'Archive discovery':id==='opportunity'?`Inspect all parts / ${inspectedParts.length} of 3`:'Investigation incomplete'}</button></div>
    </>}
  </section>;
}

export function OpportunityGuideBody(){
  const {identified,discovered}=useArchive(useShallow(s=>({identified:s.identified,discovered:s.discovered})));
  return <div className="learning-body"><p className="eyebrow">NASA EVIDENCE / MERIDIANI PLANUM</p><h2 id="learning-title">Opportunity: the journey that kept growing.</h2><p className="learning-intro">Miso follows an explorer whose greatest discoveries began with careful looking. Your recovered evidence appears below.</p><div className="learning-story"><PhotoReveal photo="opportunityRover"/><article><h3>A twin with its own story</h3><p>Opportunity launched on July 7, 2003 and landed in Meridiani Planum on January 25, 2004 UTC. It shared the design of Spirit, but explored a different part of Mars.</p><p>A chance landing inside Eagle Crater put rock outcrops within reach. Tiny mineral spheres helped scientists investigate ancient water. A sandbox on Earth later helped this robot escape a dune on Mars.</p><a href={opportunitySources.mission} target="_blank" rel="noreferrer">NASA / Opportunity mission ↗</a></article></div>
    {opportunityIds.filter(id=>identified.includes(id)).map(id=><section className="spirit-guide-record" key={id}><h3>{opportunityArtifacts[id].name}</h3><p>{id==='opportunityLog'&&!discovered.includes(id)?'Recover the mission timeline to read this record.':opportunityArtifacts[id].purpose}</p><a href={opportunityArtifacts[id].source} target="_blank" rel="noreferrer">NASA evidence ↗</a></section>)}
    <h3>How to read this reconstruction</h3><p>The 3D rover is a Blender-refined reconstruction based on NASA’s shared Spirit and Opportunity model. Added hardware detail, selection groups, separation, terrain and the nearby evidence stations are authored teaching aids. These stations combine events from different years and places; they are not an exact archaeological survey or a claim about surviving tracks. Photographs show the dates and locations in their captions. Miso’s interpretations and archive travel are fiction.</p>
    <a href={opportunitySources.model} target="_blank" rel="noreferrer">NASA / VTAD model provenance ↗</a>
  </div>;
}
