import { useEffect, useRef } from 'react';
const lunarSource='https://www.nasa.gov/wp-content/uploads/static/history/alsj/LM04_Lunar_Module_ppLV1-17.pdf';
const posters={
 structure:{title:'Structure',subtitle:'Light frame. Strong support.',lead:'This was the lander’s backbone. It held the equipment together without adding unnecessary weight.',facts:[['Support','Carried the engine, tanks and surface equipment.'],['Save mass','Lightweight construction made the journey possible.'],['Protect','Thermal coverings helped shield the spacecraft.']],equation:'LIGHT + STRONG',physics:'Every part had to earn its weight.',image:'structure',source:lunarSource},
 engine:{title:'Engine',subtitle:'A controlled way down.',lead:'A throttleable rocket engine slowed Eagle for its final descent to the Moon.',facts:[['Slow down','Thrust reduced the lander’s downward speed.'],['Adjust the push','Astronauts could increase or reduce thrust.'],['Stay behind','The descent engine remained on the Moon.']],equation:'F net = m × a',physics:'Net force changes velocity. More net force means more acceleration for the same mass.',image:'engine',source:'https://www.nasa.gov/history/apollos-lunar-module-bridged-technological-leap-to-the-moon/'},
 gear:{title:'Landing gear',subtitle:'Four legs. One safe landing.',lead:'Four legs spread the load and helped Eagle stay upright on an unfamiliar surface.',facts:[['Soften contact','Crushable honeycomb inside the struts absorbed landing energy.'],['Spread the load','Broad footpads reduced pressure on the ground.'],['Stay steady','The legs supported the descent stage after landing.']],equation:'P = F / A',physics:'For the same force, a larger contact area means less pressure.',image:'gear',source:'https://ntrs.nasa.gov/citations/19720018253'},
 reflector:{title:'Retroreflector',subtitle:'A bridge made of light.',lead:'One hundred corner-cube prisms return laser light toward its source on Earth.',facts:[['Send light','A telescope aims a laser pulse at the array.'],['Return it','Corner cubes reflect the pulse back toward its source.'],['No batteries','The array is passive: it only reflects light.']],equation:'d = c × t / 2',physics:'Time the round trip, then divide by two to find the one-way distance.',image:'reflector',source:'https://www.nasa.gov/missions/apollo/apollo-11/the-apollo-experiment-that-keeps-on-giving/'}
} as const;
function FactIcon({index}:{index:number}){return <svg viewBox="0 0 40 40" aria-hidden="true"><circle cx="20" cy="20" r="18"/>{index===0?<path d="M20 9v21m-8-8 8 8 8-8"/>:index===1?<><path d="M9 14h22M9 26h22"/><circle cx="16" cy="14" r="3"/><circle cx="25" cy="26" r="3"/></>:<><path d="M12 28V12h16v16ZM12 12l8 7 8-7M20 19v15"/></>}</svg>;}
export default function PartPoster({part,conclusion}:{part:string;conclusion?:string}){const ref=useRef<HTMLElement>(null);useEffect(()=>{if(ref.current)ref.current.scrollTop=0;},[part]);const p=posters[part as keyof typeof posters]??posters.structure;return <aside ref={ref} className="part-poster" aria-label={`${p.title} learning poster`} tabIndex={0}>
 <header className="poster-presenter"><img src="/textures/alien-cat.png" alt="Miso the alien cat"/><div><span>MISO’S FIELD GUIDE</span><p>Let’s see how it worked.</p></div></header>
 <div className="poster-heading"><p>APOLLO 11 / EAGLE</p><h3 aria-live="polite">{p.title}</h3><span>{p.subtitle}</span></div>
 <p className="poster-lead">{p.lead}</p>
 <ul className="poster-facts">{p.facts.map(([title,text],i)=><li key={title}><FactIcon index={i}/><div><strong>{title}</strong><p>{text}</p></div></li>)}</ul>
 <div className="poster-physics"><strong>{p.equation}</strong><p>{p.physics}</p></div>
 <figure className="poster-art"><div><img key={p.image} src={`/references/${p.image}-poster.png`} alt={`${p.title} concept illustration and schematic from your supplied reference`}/></div><figcaption>Concept illustration · not an engineering drawing</figcaption></figure>
 {conclusion&&<p className="evidence-conclusion poster-conclusion"><small>ALIEN INTERPRETATION</small>{conclusion}</p>}
 <a className="poster-source" href={p.source} target="_blank" rel="noreferrer">Explore the NASA source ↗</a>
 </aside>;}
