import { useEffect, useRef } from 'react';
import { PhotoReveal } from './Learning';
const lessons={
 structure:{title:'Structure',quote:'A light frame can carry a very big dream.',photo:'eagle',lines:['The frame held the parts of Eagle together.','Eagle had an upper stage and a lower stage.','The upper stage held the astronauts and controls.','The lower stage held the landing engine and tanks.','Strong beams carried these loads through the frame.','Engineers worked hard to keep the frame light.','Thin outer layers helped protect it from heat.','The lower stage became the launch pad for the trip home.','It stayed on the Moon after the upper stage left.'],equation:'Weight = mass × gravity',physics:'Less mass means less weight in the same gravity. A simple physics relationship, not a design calculation.',source:'https://www.nasa.gov/wp-content/uploads/static/history/alsj/LM04_Lunar_Module_ppLV1-17.pdf'},
 engine:{title:'Engine',quote:'Landing is a careful slow-down, not a fall.',photo:'eagle',lines:['This engine helped Eagle slow down to land.','Hot gas rushed out through the nozzle.','The push in the opposite direction is called thrust.','The crew could change how much thrust it made.','More upward thrust could slow the fall.','That control helped the crew choose a landing spot.','The engine sat under the lower stage.','It stayed on the Moon with that stage.','A different engine lifted the upper stage back into space.'],equation:'F net = m × a',physics:'The total force changes speed or direction. Here, upward thrust works against downward gravity.',source:'https://www.nasa.gov/history/apollos-lunar-module-bridged-technological-leap-to-the-moon/'},
 gear:{title:'Landing gear',quote:'Four feet helped turn a landing into a safe stop.',photo:'gear',lines:['Four legs supported Eagle on the ground.','They folded for the journey to the Moon.','Before landing, the legs opened and locked.','Wide footpads spread the load over the soil.','Inside the struts was crushable honeycomb.','It could squash to absorb landing energy.','This helped soften the shock of touchdown.','The ladder was attached to the front leg.','The legs stayed behind with the lower stage.'],equation:'Pressure = force ÷ area',physics:'A wider footpad spreads the same force over more ground, reducing pressure.',source:'https://ntrs.nasa.gov/citations/19720018253'},
 reflector:{title:'Retroreflector',quote:'What if a mirror could help measure a whole journey?',photo:'science',lines:['Apollo 11 left this array on the Moon.','It contains one hundred special glass prisms.','A telescope on Earth sends a short laser pulse.','The prisms send some light back toward Earth.','They do not need batteries to do this.','Scientists measure how long the round trip takes.','They know how fast light travels.','Time and light speed help them find the distance.','The return trip is why they divide the result by two.'],equation:'Distance = light speed × time ÷ 2',physics:'The measured time includes the trip to the Moon and back. This is a simplified explanation.',source:'https://www.nasa.gov/missions/apollo/apollo-11/the-apollo-experiment-that-keeps-on-giving/'}
} as const;
export default function PartPoster({part,conclusion}:{part:string;conclusion?:string}){
 const ref=useRef<HTMLElement>(null);const p=lessons[part as keyof typeof lessons]??lessons.structure;
 useEffect(()=>{if(ref.current)ref.current.scrollTop=0;},[part]);
 return <aside ref={ref} className="part-poster floating-lesson" aria-label={`${p.title} learning poster`} tabIndex={0}>
  <header className="poster-presenter"><img src="/textures/alien-cat.png" alt="Miso the alien cat"/><div><span>MISO’S DISCOVERY</span><p>“{p.quote}”</p></div></header>
  <div className="poster-heading"><h3 aria-live="polite">{p.title}</h3><span>{part==='reflector'?'FOLLOW THE LIGHT':'PART PULLED OUT / SCHEMATIC VIEW'}</span></div>
  <PhotoReveal key={part} photo={p.photo}/>
  <div className="lesson-prose"><p>{p.lines.slice(0,4).join(" ")}</p><p>{p.lines.slice(4).join(" ")}</p></div>
  <div className="poster-physics"><strong>{p.equation}</strong><p>{p.physics}</p></div>
  {conclusion&&<p className="evidence-conclusion poster-conclusion"><small>ALIEN INTERPRETATION</small>{conclusion}</p>}
  <a className="poster-source" href={p.source} target="_blank" rel="noreferrer">Read the NASA source ↗</a>
 </aside>;
}
